In [1]:
!pip install --upgrade pip --quiet
!pip install pandas numpy scikit-learn xgboost shap matplotlib seaborn plotly scipy statsmodels imbalanced-learn ipykernel lightgbm openpyxl --quiet

# Concept Reference — Embargo in Rolling-Window Cross-Validation

## What Problem Does Embargo Solve?

This notebook predicts **1-year and 3-year forward returns** — meaning the *target* for day 1 is "what did the stock return from day 1 to day 252?"

Now imagine your training window ends on day 1000, and your test window starts on day 1001.

The target for day 999 (in your training set) includes return data from days 999 → 1251.  
But your test window starts at day 1001 — **which is inside that future return window**.  
So the model has indirectly "seen" data from the test period while training. It's like studying from the exam paper itself.

This is called **data leakage** and it inflates CV scores in backtests but fails badly in live trading.

---

## What Embargo Does

An embargo is a **mandatory gap between the end of training and the start of testing**.

```
[ Training Data ]  ...gap (embargo)...  [ Test Data ]
     ends day 1000     252 days gap         starts day 1252
```

For a 1-year (252-day) horizon, embargo = 252 days.  
This ensures the last training sample's forward-return window **fully closes** before the test set begins.

In code (Cell 4 — `rolling_window_folds`):
```python
test_start = train_end + embargo_days   # <-- the gap
```

And in Cell 7, the embargo is set dynamically to match the horizon:
```python
rolling_window_folds(len(d), embargo_days=horizon_days)
# horizon_days = 252 for 1Y, 756 for 3Y
```

For the **3-year horizon**, the embargo is 756 days (~3 years) — which is why only 9 folds are produced instead of 13; many potential folds get skipped because there isn't enough data left after the gap.

---

## Visual Timeline

```
|<--- 5yr Train --->|<-- embargo (= horizon) -->|<-- 1yr Test -->|
    days 0–1260          days 1260–1512              days 1512–1764
```

---

## Alternatives to Embargo

| Alternative | What It Does | Tradeoff |
|---|---|---|
| **Purging** | Remove specific rows from training whose target windows overlap with the test period | More surgical than a fixed gap; common in financial ML (López de Prado's MLFS book) |
| **Hard cutoff** | Never use data past a certain date for training | Simple but wastes a lot of data |
| **Non-overlapping targets** | Predict next-day return instead of 1-year cumulative (no overlap possible) | Avoids the problem entirely but loses long-horizon signal |
| **Gap sampling** | Skip every Nth row so consecutive samples don't have overlapping windows | Reduces leakage but doesn't eliminate it |
| **Combinatorial Purged CV (CPCV)** | Advanced version — purges overlapping samples across all fold combinations | Gold standard for financial ML, but computationally expensive |

---

## Quick Reference Table

| Term | Meaning |
|---|---|
| **Leakage** | Model accidentally trained on future data |
| **Embargo** | A time gap that prevents this overlap |
| **Horizon** | How far into the future your target looks |
| **Rule of thumb** | Embargo length ≥ prediction horizon length |

> **Key tradeoff**: Bigger horizon → bigger embargo → fewer usable folds → less reliable CV estimates. This is why the 3Y horizon has fewer folds than the 1Y horizon in this notebook.

In [2]:
"""
Aurora Financial Markets Module — Step 3  (v5.1 — Dual-Horizon + Live Tail Fix)
ML-Driven Portfolio Strategy: Prediction, Optimization & Backtest
================================================================
Data   : Market_Data_Revised.xlsx (6 Indian stocks, 2005–2026)
         + Macroeconomic_QRT  (quarterly GDP growth, Inflation)
         + Macroeconomic_Annual (annual GDP growth, Inflation)

Ensemble: XGBoost + LightGBM + Random Forest
"""

import pandas as pd
import numpy as np
import warnings
import scipy.optimize as sco
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

warnings.filterwarnings("ignore")


# ─────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────

FILE          = "sample_data/Market_Data_Revised.xlsx"
RF_RATE       = 0.065    # Indian risk-free rate (~6.5% p.a.)
TRAIN_DAYS    = 1260     # Rolling training window  (~5 years)
TEST_DAYS     = 252      # Test window per fold     (~1 year)
BACKTEST_DAYS = 504      # Final backtest window    (~2 years)
EMBARGO_DAYS  = 63       # 1 quarter — prevents leakage for long-horizon targets
N_FOLDS       = 14       # Walk-forward folds anchored from 2005

# ── Prediction horizons ────────────────────────────────────────────
HORIZON_1Y = 252    # 1-year forward return (trading days)
HORIZON_3Y = 756    # 3-year forward return (trading days)

# ── BUY signal thresholds (must beat risk-free to be BUY) ─────────
BUY_THRESHOLD_1Y = RF_RATE        # annualised, e.g. 6.5%
BUY_THRESHOLD_3Y = RF_RATE        # annualised, e.g. 6.5%

# ── Model hyperparameters ──────────────────────────────────────────
XGB_PARAMS = dict(
    n_estimators=200, learning_rate=0.05, max_depth=3,
    subsample=0.8, colsample_bytree=0.8,
    reg_alpha=0.1, reg_lambda=1.0,
    random_state=42, verbosity=0, eval_metric="rmse",
)

LGBM_PARAMS = dict(
    n_estimators=200, learning_rate=0.05, max_depth=4,
    num_leaves=31, subsample=0.8, colsample_bytree=0.8,
    reg_alpha=0.1, reg_lambda=1.0,
    random_state=42, verbosity=-1, n_jobs=-1,
)

RF_PARAMS = dict(
    n_estimators=200, max_depth=5, max_features="sqrt",
    min_samples_leaf=5, random_state=42, n_jobs=-1,
)

# ── Feature list ──────────────────────────────────────────────────
FEATURES = [
    # Short-horizon price/volume signals
    "ret_1", "ret_5", "ret_20",
    "vol_5", "vol_20",
    "mom_5", "mom_20",
    "vol_ratio", "price_range",
    # Long-horizon trend/context signals
    "mom_252", "mom_756",
    "price_vs_ma252", "price_vs_ma756",
    "vol_252", "vol_ratio_sr_lr", "vol_ratio_252",
    # Macroeconomic features
    "macro_gdp_qrt", "macro_inflation_qrt",
    "macro_gdp_ann",  "macro_inflation_ann",
]

MACRO_FEATURES = {
    "macro_gdp_qrt", "macro_inflation_qrt",
    "macro_gdp_ann",  "macro_inflation_ann",
}

LONG_FEATURES = {
    "mom_252", "mom_756",
    "price_vs_ma252", "price_vs_ma756",
    "vol_252", "vol_ratio_sr_lr", "vol_ratio_252",
}

MODEL_NAMES = ["XGBoost", "LightGBM", "RandomForest"]
SEP         = "─" * 110

In [3]:
# ─────────────────────────────────────────────
# 1. LOAD MACROECONOMIC DATA
# ─────────────────────────────────────────────

def load_macro(file: str) -> pd.DataFrame:
    qrt = pd.read_excel(file, sheet_name="Macroeconomic_QRT", usecols=[0, 1, 2])
    qrt.columns = ["date", "macro_gdp_qrt", "macro_inflation_qrt"]
    qrt = qrt.dropna(subset=["date"])
    qrt["date"] = pd.to_datetime(qrt["date"])
    qrt = qrt.set_index("date").sort_index()

    ann = pd.read_excel(file, sheet_name="Macroeconomic_Annual", usecols=[0, 1, 2])
    ann.columns = ["year", "macro_gdp_ann", "macro_inflation_ann"]
    ann = ann.dropna(subset=["year"])
    ann["date"] = pd.to_datetime(ann["year"].astype(str) + "-01-01")
    ann = ann.set_index("date")[["macro_gdp_ann", "macro_inflation_ann"]].sort_index()

    full_start = min(qrt.index.min(), ann.index.min())
    full_end   = max(qrt.index.max(), ann.index.max()) + pd.offsets.YearEnd(1)
    daily_idx  = pd.date_range(full_start, full_end, freq="D")

    qrt_daily   = qrt.reindex(daily_idx).ffill()
    ann_daily   = ann.reindex(daily_idx).ffill()
    macro_daily = pd.concat([qrt_daily, ann_daily], axis=1)
    return macro_daily


# ─────────────────────────────────────────────
# 2. LOAD STOCK DATA
# ─────────────────────────────────────────────

macro_daily = load_macro(FILE)

print("Macroeconomic data loaded:")
print(f"  Quarterly → {macro_daily['macro_gdp_qrt'].dropna().index[0].date()} "
      f"to {macro_daily['macro_gdp_qrt'].dropna().index[-1].date()}")
print(f"  Annual    → {macro_daily['macro_gdp_ann'].dropna().index[0].date()} "
      f"to {macro_daily['macro_gdp_ann'].dropna().index[-1].date()}")

Macroeconomic data loaded:
  Quarterly → 2005-01-01 to 2025-12-31
  Annual    → 2005-01-01 to 2025-12-31

In [4]:
dfs        = {}
names_list = []

for i in range(1, 7):
    df   = pd.read_excel(FILE, sheet_name=f"Comp {i}")
    name = df["company_name"].iloc[0].strip()
    df   = df.sort_values("date").reset_index(drop=True)
    dfs[name] = df
    names_list.append(name)

dfs.keys()

dict_keys(['ASIAN PAINTS LTD.', 'CIPLA LTD.', 'H D F C BANK LTD.', 'I T C LTD.', 'TATA CONSULTANCY SERVICES LTD.', 'ULTRATECH CEMENT LTD.'])

The expression `d["closing"].shift(5).bfill()`.

Let's break it into two steps.

**Step 1 — what shift(5) produces**

`shift(5)` moves all values down by 5 rows, creating NaN in the first 5 positions because there is no price from 5 days before those early rows.

Example closing prices:

| Row | closing | after shift(5) |
|-----|---------|----------------|
| 0   | 100     | NaN            |
| 1   | 102     | NaN            |
| 2   | 101     | NaN            |
| 3   | 103     | NaN            |
| 4   | 104     | NaN            |
| 5   | 106     | 100            |
| 6   | 108     | 102            |
| 7   | 110     | 101            |
| 7   | 110     | 101            |

The first 5 rows are NaN because there is no row -5, -4, -3, -2, -1.

---

**Step 2 — what bfill() fills into those NaNs**

`bfill()` = **backward fill**. It looks forward in the column and fills each NaN with the **next available non-NaN value below it**.

Applying bfill to the shifted column:

| Row | after shift(5) | after bfill() |
|-----|----------------|---------------|
| 0   | NaN            | **100** ← taken from Row 5 |
| 1   | NaN            | **100** ← taken from Row 5 |
| 2   | NaN            | **100** ← taken from Row 5 |
| 3   | NaN            | **100** ← taken from Row 5 |
| 4   | NaN            | **100** ← taken from Row 5 |
| 5   | 100            | 100            |
| 6   | 102            | 102            |
| 7   | 101            | 101            |

So rows 0–4 all get filled with 100 (the first real value that appears at row 5).

---

**What mom_5 becomes for those early rows**

After bfill, the momentum calculation becomes:

$$
mom\_5(t) = \frac{P_t}{\text{bfilled value}} - 1
$$

For row 0: $\frac{100}{100} - 1 = 0\%$  
For row 1: $\frac{102}{100} - 1 = 2\%$  
For row 2: $\frac{101}{100} - 1 = 1\%$  

These are **not genuine 5-day momentum values** — they are artifacts produced by using a future price (row 5's value = 100) to fill early missing denominators.

---

**Why this is a subtle information leak**

The price 100 at row 5 is a *future value* relative to rows 0–4. Using it in the denominator means those early rows implicitly "know" about a future price. This is a backward-fill leak.

**In practice the impact is small** because:
- The notebook drops the first few rows with `dropna(subset=FEATURES)`, which tends to clean up most of these artificial early values.
- Momentum signals from 2005 or 2006 (the very start of a 20-year dataset) have minimal weight in training.

**The clean alternative** is simply not using `bfill()`:
```python
d["mom_5"] = (d["closing"] / d["closing"].shift(5) - 1).shift(1)
```
This produces NaN for the first 5 rows, which then get dropped naturally by the later `dropna` call — no leakage at all.

In [5]:
# ─────────────────────────────────────────────
# 3. FEATURE ENGINEERING  (Expanding windows + Live Tail)
# ─────────────────────────────────────────────

def make_features(df: pd.DataFrame, macro: pd.DataFrame) -> pd.DataFrame:
    d = df.copy()
    d["date"] = pd.to_datetime(d["date"])
    d = d.sort_values("date").reset_index(drop=True)

    # ── Short-horizon features ──────────────────────────────────────────
    d["ret_1"]       = d["Return"].shift(1)
    d["ret_5"]       = d["Return"].rolling(5, min_periods=1).mean().shift(1) # .rolling(5, min_periods=1). This tells pandas to look at a moving window of the last 5 rows.
    d["ret_20"]      = d["Return"].rolling(20, min_periods=1).mean().shift(1)
    d["vol_5"]       = d["Return"].rolling(5, min_periods=1).std().shift(1) # This is a measure of recent short-term volatility for last 5 days. if data exists for less than 5 days, it uses whatever is available (min_periods=1).
    d["vol_20"]      = d["Return"].rolling(20, min_periods=1).std().shift(1) # This is a measure of recent medium-term volatility for last 20 days.
    
    """ 
    .rolling() computes rolling statistics (like mean, std) over a specified window size.
    .shift(1) shifts the data down by 1 row, so that the feature values at time t are based on data up to time t-1, preventing look-ahead bias
    .bfill() fills any resulting NaN values (from the shift) with the next valid value, ensuring we don't lose rows at the start of the dataset.
    
    Short-term price momentum over about 1 week of trading.
    Positive value means price is higher than 5 trading days ago.
    Negative value means price is lower than 5 trading days ago. """

    d["mom_5"]       = (d["closing"] / d["closing"].shift(5).bfill()  - 1).shift(1)
    d["mom_20"]      = (d["closing"] / d["closing"].shift(20).bfill() - 1).shift(1)
    d["vol_ratio"]   = (d["trade Volume"] / d["trade Volume"].rolling(20, min_periods=1).mean()).shift(1)
    d["price_range"] = ((d["high"] - d["low"]) / d["closing"]).shift(1)

    # ── Long-horizon features (Expanding windows for 2005-2008) ─────────
    d["mom_252"]  = (d["closing"] / d["closing"].shift(252).bfill() - 1).shift(1)
    d["mom_756"]  = (d["closing"] / d["closing"].shift(756).bfill() - 1).shift(1)

    # price distance from 1Y moving average and 3Y moving average
    # These are regime/context features, not direct return features. 
    # They tell the model where the stock sits relative to its own long history.
    
    d["price_vs_ma252"] = (d["closing"] / d["closing"].rolling(252, min_periods=1).mean() - 1).shift(1)
    d["price_vs_ma756"] = (d["closing"] / d["closing"].rolling(756, min_periods=1).mean() - 1).shift(1)

    d["vol_252"]         = d["Return"].rolling(252, min_periods=1).std().shift(1)
    d["vol_ratio_sr_lr"] = (d["vol_20"] / d["vol_252"]).shift(1) #vol_ratio and vol_ratio_252: abnormal trading activity relative to normal baseline
    d["vol_ratio_252"]   = (d["trade Volume"] / d["trade Volume"].rolling(252, min_periods=1).mean()).shift(1)

    # ── Macro join ──────────────────────────────────────────────────────
    d = d.set_index("date")
    macro_aligned = macro.reindex(d.index, method="ffill")
    d["macro_gdp_qrt"]       = macro_aligned["macro_gdp_qrt"].shift(1)
    d["macro_inflation_qrt"] = macro_aligned["macro_inflation_qrt"].shift(1)
    d["macro_gdp_ann"]       = macro_aligned["macro_gdp_ann"].shift(1)
    d["macro_inflation_ann"] = macro_aligned["macro_inflation_ann"].shift(1)
    d = d.reset_index()

    # ── Forward return targets ──────────────────────────────────────────

    """1 + d["Return"]
    Turns daily return into daily growth factor.
    Example: if daily return is 2%, factor is 1.02. If -1%, factor is 0.99.

    rolling(HORIZON_1Y)
    Builds a moving window of length 252 trading days (for 1Y).

    apply(np.prod, raw=True)
    Multiplies all 252 daily factors in the window.
    That gives cumulative growth over the full window.

    1
    Converts cumulative growth back to cumulative return.
    If product is 1.18, return is 0.18 (18%).
    shift(-HORIZON_1Y)
    Moves that computed 252-day return upward by 252 rows so that row t gets the return from t to t+252.
    This is why it is a forward target label."""
    
    d["fwd_ret_1y"] = ((1 + d["Return"]).rolling(HORIZON_1Y).apply(np.prod, raw=True) - 1).shift(-HORIZON_1Y)
    d["fwd_ret_3y"] = ((1 + d["Return"]).rolling(HORIZON_3Y).apply(np.prod, raw=True) - 1).shift(-HORIZON_3Y)

    # 1. Neutralize toxic infinity values (caused by division by zero, e.g., zero volume)
    d = d.replace([np.inf, -np.inf], np.nan)

    # 2. Safely drop rows missing features (removes the first ~2 days, and any inf errors)
    #    CRITICAL: Does NOT drop the 2023-2026 tail where only the targets are NaN!
    d = d.dropna(subset=FEATURES).reset_index(drop=True)

    # Re-insert NaNs for the tail targets (fillna(0) affected them above)
    d.loc[d.index[-HORIZON_1Y:], "fwd_ret_1y"] = np.nan
    d.loc[d.index[-HORIZON_3Y:], "fwd_ret_3y"] = np.nan

    return d

In [6]:
# ─────────────────────────────────────────────
# 4. ROLLING-WINDOW CV FOLD BUILDER
# ─────────────────────────────────────────────

def rolling_window_folds(n_samples:    int,
                         train_days:   int = TRAIN_DAYS,
                         test_days:    int = TEST_DAYS,
                         embargo_days: int = EMBARGO_DAYS,
                         n_folds:      int = N_FOLDS):
    for k in range(n_folds):
        train_start = k * test_days
        train_end   = train_start + train_days
        test_start  = train_end + embargo_days
        test_end    = test_start + test_days

        if test_end > n_samples:
            break

        yield (
            np.arange(train_start, train_end),
            np.arange(test_start,  test_end),
        )

In [7]:
# ─────────────────────────────────────────────
# 5. INSTANTIATE MODELS
# ─────────────────────────────────────────────

def build_models():
    return {
        "XGBoost":      XGBRegressor(**XGB_PARAMS),
        "LightGBM":     LGBMRegressor(**LGBM_PARAMS),
        "RandomForest": RandomForestRegressor(**RF_PARAMS),
    }


# ─────────────────────────────────────────────
# 6. SOFTMAX WEIGHT HELPER
# ─────────────────────────────────────────────

def softmax_weights(scores: np.ndarray, temperature: float = 0.1) -> np.ndarray:
    scores  = np.array(scores, dtype=float)
    shifted = (scores - scores.max()) / temperature
    exp_s   = np.exp(shifted)
    return exp_s / exp_s.sum()

In [8]:
dfs['ASIAN PAINTS LTD.']

,company_code,company_name,date,opening,high,low,closing,trade Volume,Return
0,22859,ASIAN PAINTS LTD.,2005-01-03,320.10,325.00,318.60,319.10,17273,-0.003124
1,22859,ASIAN PAINTS LTD.,2005-01-04,322.00,324.90,320.00,324.05,32240,0.006366
2,22859,ASIAN PAINTS LTD.,2005-01-05,324.05,324.95,320.00,321.85,30500,-0.006789
3,22859,ASIAN PAINTS LTD.,2005-01-06,327.00,327.00,302.55,309.45,38985,-0.053670
4,22859,ASIAN PAINTS LTD.,2005-01-07,310.00,322.00,309.10,320.05,17621,0.032419
...,...,...,...,...,...,...,...,...,...
5245,22859,ASIAN PAINTS LTD.,2026-02-23,2424.70,2446.60,2411.50,2429.70,634365,0.002062
5246,22859,ASIAN PAINTS LTD.,2026-02-24,2413.00,2441.50,2403.70,2413.10,499660,0.000041
5247,22859,ASIAN PAINTS LTD.,2026-02-25,2416.00,2427.90,2400.00,2416.40,526764,0.000166
5248,22859,ASIAN PAINTS LTD.,2026-02-26,2416.10,2422.20,2382.00,2394.90,588742,-0.008774
5249,22859,ASIAN PAINTS LTD.,2026-02-27,2385.00,2397.60,2359.00,2376.20,2531619,-0.003690

In [9]:
make_features(dfs['ASIAN PAINTS LTD.'], macro_daily)

,date,company_code,company_name,opening,high,low,closing,trade Volume,Return,ret_1,...,price_vs_ma756,vol_252,vol_ratio_sr_lr,vol_ratio_252,macro_gdp_qrt,macro_inflation_qrt,macro_gdp_ann,macro_inflation_ann,fwd_ret_1y,fwd_ret_3y
0,2005-01-06,22859,ASIAN PAINTS LTD.,327.0,327.00,302.55,309.45,38985,-0.053670,-0.006789,...,0.000570,0.006789,1.000000,1.143564,3.916985,0.254453,7.923431,4.246344,-0.166287,-0.532212
1,2005-01-07,22859,ASIAN PAINTS LTD.,310.0,322.00,309.10,320.05,17621,0.032419,-0.053670,...,-0.028758,0.026823,1.000000,1.310442,3.916985,0.254453,7.923431,4.246344,-0.201428,-0.577773
2,2005-01-10,22859,ASIAN PAINTS LTD.,323.0,324.00,317.05,321.80,17363,-0.003715,0.032419,...,0.003606,0.031244,1.000000,0.644896,3.916985,0.254453,7.923431,4.246344,-0.223381,-0.581135
3,2005-01-11,22859,ASIAN PAINTS LTD.,318.1,321.95,318.05,320.30,24322,0.006916,-0.003715,...,0.007567,0.027950,1.000000,0.676560,3.916985,0.254453,7.923431,4.246344,-0.234533,-0.581412
4,2005-01-12,22859,ASIAN PAINTS LTD.,320.0,320.00,312.00,316.90,14280,-0.009688,0.006916,...,0.002459,0.025894,1.000000,0.954852,3.916985,0.254453,7.923431,4.246344,-0.228622,-0.584067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5242,2026-02-23,22859,ASIAN PAINTS LTD.,2424.7,2446.60,2411.50,2429.70,634365,0.002062,0.020982,...,-0.133564,0.013264,1.331556,0.657100,12.136078,-0.024015,6.494766,4.953036,NaN,NaN
5243,2026-02-24,22859,ASIAN PAINTS LTD.,2413.0,2441.50,2403.70,2413.10,499660,0.000041,0.002062,...,-0.132861,0.013263,1.405211,0.528729,12.136078,-0.024015,6.494766,4.953036,NaN,NaN
5244,2026-02-25,22859,ASIAN PAINTS LTD.,2416.0,2427.90,2400.00,2416.40,526764,0.000166,0.000041,...,-0.138645,0.013253,1.310346,0.417040,12.136078,-0.024015,6.494766,4.953036,NaN,NaN
5245,2026-02-26,22859,ASIAN PAINTS LTD.,2416.1,2422.20,2382.00,2394.90,588742,-0.008774,0.000166,...,-0.137324,0.013249,1.310714,0.439967,12.136078,-0.024015,6.494766,4.953036,NaN,NaN
5246,2026-02-27,22859,ASIAN PAINTS LTD.,2385.0,2397.60,2359.00,2376.20,2531619,-0.003690,-0.008774,...,-0.144831,0.013261,1.163105,0.491825,12.136078,-0.024015,6.494766,4.953036,NaN,NaN

In [10]:
make_features(dfs['CIPLA LTD.'],macro_daily)

,date,company_code,company_name,opening,high,low,closing,trade Volume,Return,ret_1,...,price_vs_ma756,vol_252,vol_ratio_sr_lr,vol_ratio_252,macro_gdp_qrt,macro_inflation_qrt,macro_gdp_ann,macro_inflation_ann,fwd_ret_1y,fwd_ret_3y
0,2005-01-06,47858,CIPLA LTD.,302.00,302.7,289.05,292.65,1299361,-0.030960,-0.052159,...,-0.037805,0.026680,1.000000,1.208557,3.916985,0.254453,7.923431,4.246344,-0.597807,-0.893278
1,2005-01-07,47858,CIPLA LTD.,293.00,295.9,289.10,291.75,927534,-0.004266,-0.030960,...,-0.048563,0.022281,1.000000,1.184090,3.916985,0.254453,7.923431,4.246344,-0.592145,-0.896871
2,2005-01-10,47858,CIPLA LTD.,292.00,297.9,279.00,281.90,1325949,-0.034589,-0.004266,...,-0.041620,0.021207,1.000000,0.872245,3.916985,0.254453,7.923431,4.246344,-0.577628,-0.889695
3,2005-01-11,47858,CIPLA LTD.,282.00,284.0,265.50,268.15,1699809,-0.049113,-0.034589,...,-0.062417,0.019881,1.000000,1.197627,3.916985,0.254453,7.923431,4.246344,-0.553188,-0.880055
4,2005-01-12,47858,CIPLA LTD.,270.05,272.7,245.00,252.80,2556180,-0.063877,-0.049113,...,-0.094153,0.020762,1.000000,1.426238,3.916985,0.254453,7.923431,4.246344,-0.528843,-0.876385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5242,2026-02-23,47858,CIPLA LTD.,1335.90,1335.9,1308.80,1326.50,2435610,-0.007036,0.009181,...,-0.020207,0.011911,1.189526,1.024682,12.136078,-0.024015,6.494766,4.953036,NaN,NaN
5243,2026-02-24,47858,CIPLA LTD.,1326.00,1338.5,1316.50,1326.70,2109672,0.000528,-0.007036,...,-0.031152,0.011893,0.946026,1.605280,12.136078,-0.024015,6.494766,4.953036,NaN,NaN
5244,2026-02-25,47858,CIPLA LTD.,1326.70,1349.0,1326.70,1346.10,1018377,0.014623,0.000528,...,-0.031282,0.011870,0.927640,1.386846,12.136078,-0.024015,6.494766,4.953036,NaN,NaN
5245,2026-02-26,47858,CIPLA LTD.,1352.80,1364.9,1343.30,1358.10,2013877,0.003918,0.014623,...,-0.017408,0.011901,0.891326,0.669367,12.136078,-0.024015,6.494766,4.953036,NaN,NaN
5246,2026-02-27,47858,CIPLA LTD.,1353.00,1356.9,1338.50,1348.20,2609711,-0.003548,0.003918,...,-0.008971,0.011897,0.944724,1.320929,12.136078,-0.024015,6.494766,4.953036,NaN,NaN

In [11]:
# ─────────────────────────────────────────────
# 7. ROLLING-WINDOW CV + ENSEMBLE (Live Tail Inference)
# ─────────────────────────────────────────────

cv_summary       = {}
backtest_results = {}
pred_returns     = {"1Y": {}, "3Y": {}}

print(f"\n{'═'*110}")
print("  ENSEMBLE ROLLING-WINDOW CV  —  DUAL HORIZON: 1-Year & 3-Year Forward Returns")
print(f"  Training : {TRAIN_DAYS} days (~5 yrs)  │  Test : {TEST_DAYS} days (~1 yr)")
print(f"{'═'*110}\n")

for name in names_list:
    short = name.replace(" LTD.", "").strip()
    d     = make_features(dfs[name], macro_daily)
    X     = d[FEATURES].values
    dates = d["date"].values

    print(f"\n  {'▶'*2} {short}  (Data length: {len(d)} rows | {d['date'].iloc[0].date()} → {d['date'].iloc[-1].date()})")

    results_by_horizon = {}

    for horizon_label, target_col, horizon_days, rf_threshold in [
        ("1Y", "fwd_ret_1y", HORIZON_1Y, BUY_THRESHOLD_1Y),
        ("3Y", "fwd_ret_3y", HORIZON_3Y, BUY_THRESHOLD_3Y * 3),
    ]:
        y = d[target_col].values

        print(f"\n  ── Horizon : {horizon_label} Forward Return ───────────────────────")

        fold_metrics    = []
        model_hit_rates = {m: [] for m in MODEL_NAMES}

        # Pass horizon_days as the embargo to purge the overlap!
        for fold_num, (tr_idx, te_idx) in enumerate(rolling_window_folds(len(d), embargo_days=horizon_days), start=1):
            X_tr, y_tr = X[tr_idx], y[tr_idx]
            X_te, y_te = X[te_idx], y[te_idx]

            # Skip folds that extend into the missing-target tail
            if np.isnan(y_tr).any() or np.isnan(y_te).any():
                continue

            scaler = StandardScaler()
            X_tr_s = scaler.fit_transform(X_tr)
            X_te_s = scaler.transform(X_te)

            models = build_models()
            preds  = {}
            hits   = {}

            for mname, model in models.items():
                model.fit(X_tr_s, y_tr)
                p = model.predict(X_te_s)
                preds[mname] = p
                hits[mname] = float(np.mean((p > rf_threshold) == (y_te > rf_threshold)))
                model_hit_rates[mname].append(hits[mname])

            ens_pred = np.mean([preds[m] for m in MODEL_NAMES], axis=0)
            ens_hit  = float(np.mean((ens_pred > rf_threshold) == (y_te > rf_threshold)))
            ens_rmse = float(np.sqrt(mean_squared_error(y_te, ens_pred)))
            ens_r2   = float(r2_score(y_te, ens_pred))

            test_start_dt = pd.Timestamp(dates[te_idx[0]]).date()
            test_end_dt   = pd.Timestamp(dates[te_idx[-1]]).date()

            print(f"  Fold {fold_num:<2} {str(test_start_dt)+' → '+str(test_end_dt):<26} "
                  f"Ens Hit: {ens_hit:>7.1%} | R²: {ens_r2:>6.4f}")

            fold_metrics.append({
                "fold": fold_num, "hits": hits, "ens_hit": ens_hit,
                "ens_rmse": ens_rmse, "ens_r2": ens_r2,
                "preds": preds, "actual": y_te, "test_dates": dates[te_idx],
            })

        if not fold_metrics:
            print(f"  ⚠  No valid folds for {horizon_label}.")
            results_by_horizon[horizon_label] = None
            continue

        mean_hits     = {m: np.mean(model_hit_rates[m]) for m in MODEL_NAMES}
        blend_weights = softmax_weights([mean_hits[m] for m in MODEL_NAMES], temperature=0.1)
        blend_w_dict  = dict(zip(MODEL_NAMES, blend_weights))

        cv_ens_hit     = np.mean([m["ens_hit"]  for m in fold_metrics])
        cv_ens_rmse    = np.mean([m["ens_rmse"] for m in fold_metrics])
        cv_ens_r2      = np.mean([m["ens_r2"]   for m in fold_metrics])
        cv_ens_hit_std = np.std ([m["ens_hit"]  for m in fold_metrics])

        # ── Final model fitting for backtest ────────────────────────────
        # Use horizon_days to dynamically purge the gap before the backtest window
        final_train_end = len(d) - BACKTEST_DAYS - horizon_days
        final_train_idx = np.arange(max(0, final_train_end - TRAIN_DAYS), final_train_end)
        final_test_idx  = np.arange(final_train_end + horizon_days, len(d))

        valid_train = [i for i in final_train_idx if not np.isnan(y[i])]
        valid_test  = [i for i in final_test_idx  if not np.isnan(y[i])]

        if len(valid_train) == 0:
            continue

        X_ftr, y_ftr = X[valid_train], y[valid_train]
        scaler_f = StandardScaler()
        X_ftr_s  = scaler_f.fit_transform(X_ftr)

        final_models = build_models()
        final_fi     = {}

        for mname, model in final_models.items():
            model.fit(X_ftr_s, y_ftr)
            if hasattr(model, "feature_importances_"):
                final_fi[mname] = dict(zip(FEATURES, model.feature_importances_))

        # ── Backtest execution (on valid test targets) ─────────────────
        bt_hit = np.nan
        final_ens = np.array([])
        y_fte = np.array([])

        if len(valid_test) > 0:
            X_fte, y_fte = X[valid_test], y[valid_test]
            X_fte_s = scaler_f.transform(X_fte)
            final_preds = {m: final_models[m].predict(X_fte_s) for m in MODEL_NAMES}
            final_ens = sum(blend_w_dict[m] * final_preds[m] for m in MODEL_NAMES)
            bt_hit = float(np.mean((final_ens > rf_threshold) == (y_fte > rf_threshold)))

        # ── LIVE INFERENCE (For Today's Allocation) ────────────────────
        X_live   = X[-1].reshape(1, -1)
        X_live_s = scaler_f.transform(X_live)

        live_preds = {m: final_models[m].predict(X_live_s)[0] for m in MODEL_NAMES}
        live_ens   = sum(blend_w_dict[m] * live_preds[m] for m in MODEL_NAMES)

        years    = 1 if horizon_label == "1Y" else 3
        pred_ann = float((1 + live_ens) ** (1 / years) - 1)

        pred_returns[horizon_label][name] = pred_ann

        print(f"  Live Signal ({horizon_label}) for {d['date'].iloc[-1].date()}: {pred_ann:.2%}")

        results_by_horizon[horizon_label] = {
            "cv_hit": cv_ens_hit, "cv_rmse": cv_ens_rmse, "cv_r2": cv_ens_r2,
            "cv_hit_std": cv_ens_hit_std, "mean_hits": mean_hits,
            "blend_weights": blend_w_dict, "fold_metrics": fold_metrics,
            "final_ens": final_ens, "y_fte": y_fte, "final_fi": final_fi,
            "pred_ann_ret": pred_ann, "bt_hit": bt_hit,
            "rf_threshold": rf_threshold, "years": years,
        }

    cv_summary[name]       = results_by_horizon
    backtest_results[name] = results_by_horizon

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  ENSEMBLE ROLLING-WINDOW CV  —  DUAL HORIZON: 1-Year & 3-Year Forward Returns
  Training : 1260 days (~5 yrs)  │  Test : 252 days (~1 yr)
══════════════════════════════════════════════════════════════════════════════════════════════════════════════


  ▶▶ ASIAN PAINTS  (Data length: 5247 rows | 2005-01-06 → 2026-02-27)

  ── Horizon : 1Y Forward Return ───────────────────────
  Fold 1  2011-02-07 → 2012-02-09    Ens Hit:   36.5% | R²: -1.1985
  Fold 2  2012-02-10 → 2013-02-11    Ens Hit:   52.4% | R²: -0.6263
  Fold 3  2013-02-12 → 2014-02-13    Ens Hit:   57.9% | R²: -13.7107
  Fold 4  2014-02-14 → 2015-02-27    Ens Hit:   31.0% | R²: -29.6698
  Fold 5  2015-02-28 → 2016-03-03    Ens Hit:   23.8% | R²: -11.4077
  Fold 6  2016-03-04 → 2017-03-14    Ens Hit:  100.0% | R²: 0.3166
  Fold 7  2017-03-15 → 2018-03-19    Ens Hit:   82.9% | R²: -0.5547
  Fold 8  2018-03-20 → 2019-03-26    Ens Hit:  100.0% | R²: -0.2619
  Fold 9  2019-03-27 → 2020-04-03    Ens Hit:   85.7% | R²: 0.2384
  Fold 10 2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: -0.3595
  Fold 11 2021-04-09 → 2022-04-13    Ens Hit:   99.6% | R²: -2.9483
  Fold 12 2022-04-18 → 2023-04-21    Ens Hit:  100.0% | R²: -0.2385
  Fold 13 2023-04-24 → 2024-04-26    Ens Hit:  100.0% | R²: -4.4374
  Live Signal (1Y) for 2026-02-27: -6.85%

  ── Horizon : 3Y Forward Return ───────────────────────
  Fold 1  2013-02-12 → 2014-02-13    Ens Hit:  100.0% | R²: -19.6567
  Fold 2  2014-02-14 → 2015-02-27    Ens Hit:   76.2% | R²: -185.3812
  Fold 3  2015-02-28 → 2016-03-03    Ens Hit:    0.0% | R²: -299.1939
  Fold 4  2016-03-04 → 2017-03-14    Ens Hit:   59.9% | R²: -18.6051
  Fold 5  2017-03-15 → 2018-03-19    Ens Hit:  100.0% | R²: -10.4287
  Fold 6  2018-03-20 → 2019-03-26    Ens Hit:  100.0% | R²: -8.7654
  Fold 7  2019-03-27 → 2020-04-03    Ens Hit:   97.2% | R²: -6.5939
  Fold 8  2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: -16.8752
  Fold 9  2021-04-09 → 2022-04-13    Ens Hit:  100.0% | R²: -2.7638
  Live Signal (3Y) for 2026-02-27: -13.74%

  ▶▶ CIPLA  (Data length: 5247 rows | 2005-01-06 → 2026-02-27)

  ── Horizon : 1Y Forward Return ───────────────────────
  Fold 1  2011-02-07 → 2012-02-09    Ens Hit:  100.0% | R²: -14.5416
  Fold 2  2012-02-10 → 2013-02-11    Ens Hit:  100.0% | R²: -4.9628
  Fold 3  2013-02-12 → 2014-02-13    Ens Hit:  100.0% | R²: -4.0837
  Fold 4  2014-02-14 → 2015-02-27    Ens Hit:  100.0% | R²: 0.4958
  Fold 5  2015-02-28 → 2016-03-03    Ens Hit:  100.0% | R²: -0.5211
  Fold 6  2016-03-04 → 2017-03-14    Ens Hit:  100.0% | R²: -2.1548
  Fold 7  2017-03-15 → 2018-03-19    Ens Hit:  100.0% | R²: -9.3451
  Fold 8  2018-03-20 → 2019-03-26    Ens Hit:  100.0% | R²: -1.2580
  Fold 9  2019-03-27 → 2020-04-03    Ens Hit:  100.0% | R²: -2.4114
  Fold 10 2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: -1.1703
  Fold 11 2021-04-09 → 2022-04-13    Ens Hit:   79.4% | R²: -7.1733
  Fold 12 2022-04-18 → 2023-04-21    Ens Hit:  100.0% | R²: -1.2502
  Fold 13 2023-04-24 → 2024-04-26    Ens Hit:  100.0% | R²: -8.0718
  Live Signal (1Y) for 2026-02-27: -34.05%

  ── Horizon : 3Y Forward Return ───────────────────────
  Fold 1  2013-02-12 → 2014-02-13    Ens Hit:  100.0% | R²: -1.0099
  Fold 2  2014-02-14 → 2015-02-27    Ens Hit:  100.0% | R²: -0.9430
  Fold 3  2015-02-28 → 2016-03-03    Ens Hit:  100.0% | R²: -42.8646
  Fold 4  2016-03-04 → 2017-03-14    Ens Hit:  100.0% | R²: -2.4579
  Fold 5  2017-03-15 → 2018-03-19    Ens Hit:  100.0% | R²: -6.5750
  Fold 6  2018-03-20 → 2019-03-26    Ens Hit:  100.0% | R²: -8.8407
  Fold 7  2019-03-27 → 2020-04-03    Ens Hit:  100.0% | R²: -1.3946
  Fold 8  2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: -3.8119
  Fold 9  2021-04-09 → 2022-04-13    Ens Hit:  100.0% | R²: -48.1349
  Live Signal (3Y) for 2026-02-27: -31.92%

  ▶▶ H D F C BANK  (Data length: 5247 rows | 2005-01-06 → 2026-02-27)

  ── Horizon : 1Y Forward Return ───────────────────────
  Fold 1  2011-02-07 → 2012-02-09    Ens Hit:   73.0% | R²: 0.0749
  Fold 2  2012-02-10 → 2013-02-11    Ens Hit:   50.0% | R²: -0.0963
  Fold 3  2013-02-12 → 2014-02-13    Ens Hit:   70.2% | R²: 0.1649
  Fold 4  2014-02-14 → 2015-02-27    Ens Hit:   96.4% | R²: -1.7958
  Fold 5  2015-02-28 → 2016-03-03    Ens Hit:   59.5% | R²: -2.2690
  Fold 6  2016-03-04 → 2017-03-14    Ens Hit:    2.0% | R²: -8.2015
  Fold 7  2017-03-15 → 2018-03-19    Ens Hit:   40.5% | R²: -1.6576
  Fold 8  2018-03-20 → 2019-03-26    Ens Hit:    6.0% | R²: -4.8504
  Fold 9  2019-03-27 → 2020-04-03    Ens Hit:    7.5% | R²: -124.2825
  Fold 10 2020-04-07 → 2021-04-08    Ens Hit:   93.3% | R²: 0.0508
  Fold 11 2021-04-09 → 2022-04-13    Ens Hit:   17.1% | R²: -2.7593
  Fold 12 2022-04-18 → 2023-04-21    Ens Hit:   69.4% | R²: -0.0643
  Fold 13 2023-04-24 → 2024-04-26    Ens Hit:   43.7% | R²: -1.2321
  Live Signal (1Y) for 2026-02-27: -0.03%

  ── Horizon : 3Y Forward Return ───────────────────────
  Fold 1  2013-02-12 → 2014-02-13    Ens Hit:    2.4% | R²: -27.5024
  Fold 2  2014-02-14 → 2015-02-27    Ens Hit:   58.7% | R²: -4.5916
  Fold 3  2015-02-28 → 2016-03-03    Ens Hit:   84.1% | R²: -1.2359
  Fold 4  2016-03-04 → 2017-03-14    Ens Hit:   66.3% | R²: -0.8223
  Fold 5  2017-03-15 → 2018-03-19    Ens Hit:  100.0% | R²: -18.5579
  Fold 6  2018-03-20 → 2019-03-26    Ens Hit:  100.0% | R²: -525.1705
  Fold 7  2019-03-27 → 2020-04-03    Ens Hit:   97.2% | R²: -15.1173
  Fold 8  2020-04-07 → 2021-04-08    Ens Hit:   64.3% | R²: -3.6433
  Fold 9  2021-04-09 → 2022-04-13    Ens Hit:   38.1% | R²: -1.5493
  Live Signal (3Y) for 2026-02-27: -2.47%

  ▶▶ I T C  (Data length: 5247 rows | 2005-01-06 → 2026-02-27)

  ── Horizon : 1Y Forward Return ───────────────────────
  Fold 1  2011-02-07 → 2012-02-09    Ens Hit:    5.2% | R²: -16.2151
  Fold 2  2012-02-10 → 2013-02-11    Ens Hit:   36.9% | R²: -1.1007
  Fold 3  2013-02-12 → 2014-02-13    Ens Hit:   16.3% | R²: -7.1691
  Fold 4  2014-02-14 → 2015-02-27    Ens Hit:   25.0% | R²: -13.2893
  Fold 5  2015-02-28 → 2016-03-03    Ens Hit:   50.4% | R²: -0.6077
  Fold 6  2016-03-04 → 2017-03-14    Ens Hit:   92.9% | R²: -0.6723
  Fold 7  2017-03-15 → 2018-03-19    Ens Hit:   22.6% | R²: -38.9853
  Fold 8  2018-03-20 → 2019-03-26    Ens Hit:   77.0% | R²: -20.5861
  Fold 9  2019-03-27 → 2020-04-03    Ens Hit:  100.0% | R²: -66.8622
  Fold 10 2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: -2.5426
  Fold 11 2021-04-09 → 2022-04-13    Ens Hit:   20.6% | R²: -7.3584
  Fold 12 2022-04-18 → 2023-04-21    Ens Hit:   70.6% | R²: -1.3902
  Fold 13 2023-04-24 → 2024-04-26    Ens Hit:  100.0% | R²: -11.2276
  Live Signal (1Y) for 2026-02-27: -34.91%

  ── Horizon : 3Y Forward Return ───────────────────────
  Fold 1  2013-02-12 → 2014-02-13    Ens Hit:   88.1% | R²: -38.0266
  Fold 2  2014-02-14 → 2015-02-27    Ens Hit:   11.1% | R²: -21.8449
  Fold 3  2015-02-28 → 2016-03-03    Ens Hit:  100.0% | R²: -18.7407
  Fold 4  2016-03-04 → 2017-03-14    Ens Hit:  100.0% | R²: -71.0662
  Fold 5  2017-03-15 → 2018-03-19    Ens Hit:  100.0% | R²: -3692.4863
  Fold 6  2018-03-20 → 2019-03-26    Ens Hit:  100.0% | R²: -3854.5937
  Fold 7  2019-03-27 → 2020-04-03    Ens Hit:   96.4% | R²: -48.1777
  Fold 8  2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: -12.5977
  Fold 9  2021-04-09 → 2022-04-13    Ens Hit:  100.0% | R²: -46.0526
  Live Signal (3Y) for 2026-02-27: -25.43%

  ▶▶ TATA CONSULTANCY SERVICES  (Data length: 5247 rows | 2005-01-06 → 2026-02-27)

  ── Horizon : 1Y Forward Return ───────────────────────
  Fold 1  2011-02-07 → 2012-02-09    Ens Hit:   69.8% | R²: -16.0656
  Fold 2  2012-02-10 → 2013-02-11    Ens Hit:    3.2% | R²: -15.4977
  Fold 3  2013-02-12 → 2014-02-13    Ens Hit:   53.6% | R²: -0.4275
  Fold 4  2014-02-14 → 2015-02-27    Ens Hit:   21.4% | R²: -81.5861
  Fold 5  2015-02-28 → 2016-03-03    Ens Hit:   10.3% | R²: -16.4485
  Fold 6  2016-03-04 → 2017-03-14    Ens Hit:   61.5% | R²: -1.3938
  Fold 7  2017-03-15 → 2018-03-19    Ens Hit:   20.6% | R²: -0.8211
  Fold 8  2018-03-20 → 2019-03-26    Ens Hit:    9.9% | R²: -45.8083
  Fold 9  2019-03-27 → 2020-04-03    Ens Hit:   11.5% | R²: -7.8595
  Fold 10 2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: -3.6932
  Fold 11 2021-04-09 → 2022-04-13    Ens Hit:  100.0% | R²: 0.3200
  Fold 12 2022-04-18 → 2023-04-21    Ens Hit:   80.2% | R²: -0.3064
  Fold 13 2023-04-24 → 2024-04-26    Ens Hit:   58.7% | R²: -0.8320
  Live Signal (1Y) for 2026-02-27: -15.61%

  ── Horizon : 3Y Forward Return ───────────────────────
  Fold 1  2013-02-12 → 2014-02-13    Ens Hit:  100.0% | R²: -2.9930
  Fold 2  2014-02-14 → 2015-02-27    Ens Hit:  100.0% | R²: -14.3324
  Fold 3  2015-02-28 → 2016-03-03    Ens Hit:   77.8% | R²: -17.3081
  Fold 4  2016-03-04 → 2017-03-14    Ens Hit:   99.2% | R²: -1.0675
  Fold 5  2017-03-15 → 2018-03-19    Ens Hit:   19.4% | R²: -31.2001
  Fold 6  2018-03-20 → 2019-03-26    Ens Hit:   20.6% | R²: -226.1891
  Fold 7  2019-03-27 → 2020-04-03    Ens Hit:    0.0% | R²: -72.6612
  Fold 8  2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: -12.2247
  Fold 9  2021-04-09 → 2022-04-13    Ens Hit:  100.0% | R²: -1.4301
  Live Signal (3Y) for 2026-02-27: -8.14%

  ▶▶ ULTRATECH CEMENT  (Data length: 5247 rows | 2005-01-06 → 2026-02-27)

  ── Horizon : 1Y Forward Return ───────────────────────
  Fold 1  2011-02-07 → 2012-02-09    Ens Hit:    0.0% | R²: -19.7867
  Fold 2  2012-02-10 → 2013-02-11    Ens Hit:   29.8% | R²: -4.0407
  Fold 3  2013-02-12 → 2014-02-13    Ens Hit:   71.8% | R²: -7.8671
  Fold 4  2014-02-14 → 2015-02-27    Ens Hit:   25.8% | R²: -19.8721
  Fold 5  2015-02-28 → 2016-03-03    Ens Hit:    0.0% | R²: -59.6536
  Fold 6  2016-03-04 → 2017-03-14    Ens Hit:   94.0% | R²: -0.2317
  Fold 7  2017-03-15 → 2018-03-19    Ens Hit:   89.7% | R²: -11.3191
  Fold 8  2018-03-20 → 2019-03-26    Ens Hit:   23.4% | R²: -25.5914
  Fold 9  2019-03-27 → 2020-04-03    Ens Hit:   78.2% | R²: -5.1404
  Fold 10 2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: 0.2118
  Fold 11 2021-04-09 → 2022-04-13    Ens Hit:  100.0% | R²: -0.8997
  Fold 12 2022-04-18 → 2023-04-21    Ens Hit:  100.0% | R²: 0.3158
  Fold 13 2023-04-24 → 2024-04-26    Ens Hit:   97.2% | R²: -4.1029
  Live Signal (1Y) for 2026-02-27: -30.18%

  ── Horizon : 3Y Forward Return ───────────────────────
  Fold 1  2013-02-12 → 2014-02-13    Ens Hit:   32.5% | R²: -52.3480
  Fold 2  2014-02-14 → 2015-02-27    Ens Hit:  100.0% | R²: -1.0196
  Fold 3  2015-02-28 → 2016-03-03    Ens Hit:   61.5% | R²: -409.4005
  Fold 4  2016-03-04 → 2017-03-14    Ens Hit:    0.0% | R²: -478.4031
  Fold 5  2017-03-15 → 2018-03-19    Ens Hit:   78.2% | R²: -340.6651
  Fold 6  2018-03-20 → 2019-03-26    Ens Hit:    2.4% | R²: -456.9022
  Fold 7  2019-03-27 → 2020-04-03    Ens Hit:    0.0% | R²: -765.5517
  Fold 8  2020-04-07 → 2021-04-08    Ens Hit:  100.0% | R²: -77.8557
  Fold 9  2021-04-09 → 2022-04-13    Ens Hit:  100.0% | R²: 0.3572
  Live Signal (3Y) for 2026-02-27: -20.96%

In [12]:
cv_summary

{'ASIAN PAINTS LTD.': {'1Y': {'cv_hit': np.float64(0.7460317460317459),
   'cv_rmse': np.float64(0.21571250946461554),
   'cv_r2': np.float64(-4.989096057065817),
   'cv_hit_std': np.float64(0.28757786620253056),
   'mean_hits': {'XGBoost': np.float64(0.6932234432234432),
    'LightGBM': np.float64(0.7509157509157508),
    'RandomForest': np.float64(0.7155067155067154)},
   'blend_weights': {'XGBoost': np.float64(0.24812892807462716),
    'LightGBM': np.float64(0.4418063037730408),
    'RandomForest': np.float64(0.3100647681523321)},
   'fold_metrics': [{'fold': 1,
     'hits': {'XGBoost': 0.38492063492063494,
      'LightGBM': 0.376984126984127,
      'RandomForest': 0.3531746031746032},
     'ens_hit': 0.36507936507936506,
     'ens_rmse': 0.22513713597350893,
     'ens_r2': -1.1985461656366656,
     'preds': {'XGBoost': array([-0.1044765 , -0.07489797, -0.06424744, -0.06205198, -0.06330624,
             -0.06381287, -0.07357074, -0.07105547, -0.07529718, -0.07756619,
             -0.07810199, -0.07385571, -0.06268528, -0.1038496 ,  0.12167266,
              0.12129943,  0.13022092, -0.1031397 , -0.1025662 , -0.07531757,
             -0.10237852, -0.10074192, -0.09764866, -0.09178157, -0.07664663,
             -0.07874086, -0.08439672, -0.06073184, -0.06864684, -0.05983721,
             -0.0578994 , -0.05051345, -0.05760656, -0.07322124, -0.06419297,
             -0.04958172, -0.08476066, -0.09334514, -0.06924706,  0.00816531,
             -0.02849077, -0.0196884 , -0.01411537,  0.00313788, -0.00143055,
             -0.00896924, -0.01648387, -0.03721721, -0.02588501, -0.01460617,
             -0.01363939, -0.0156915 , -0.01091216, -0.03339109, -0.0265106 ,
             -0.01081111, -0.01402787, -0.01330805, -0.01556916, -0.0100854 ,
             -0.02299038, -0.0232034 , -0.01423088, -0.01244849, -0.02804156,
             -0.01389906, -0.02918332, -0.01329324, -0.01495901, -0.01902544,
             -0.01623368, -0.02773543, -0.03013776, -0.04245425, -0.04385426,
             -0.03981364, -0.04564346, -0.05634929, -0.0527474 , -0.06564738,
             -0.05010387, -0.06075988, -0.05418629, -0.07537879, -0.0779385 ,
             -0.06337774, -0.06361679, -0.04578225, -0.04637067, -0.04801538,
             -0.04428135, -0.03105282, -0.02125242, -0.02781472, -0.02650659,
             -0.02065559, -0.03616078, -0.06063149, -0.06776186, -0.07163674,
             -0.06650923, -0.05798222, -0.05153228, -0.03463379, -0.0370312 ,
             -0.02954924, -0.02682328, -0.02359156, -0.00693526, -0.01025418,
             -0.01298856, -0.01604853, -0.00580218,  0.00307871,  0.00743984,
              0.00444459, -0.06592643, -0.06329737, -0.06885438, -0.06690245,
             -0.0745628 , -0.07706792, -0.04739982, -0.05672041,  0.02452358,
             -0.05651796, -0.05134999, -0.05878088, -0.06897677, -0.06647912,
             -0.06567704, -0.08655463, -0.08616123, -0.08425773, -0.00741958,
              0.00468295, -0.01873589, -0.0151379 , -0.0031858 , -0.02028773,
             -0.02345731, -0.01749655, -0.01549963, -0.0220436 , -0.02113157,
             -0.02417016, -0.00457679,  0.01486855,  0.01031099,  0.02411479,
              0.03409494,  0.03493677,  0.02002405,  0.06875205,  0.02572646,
              0.05845865,  0.05413909,  0.02414137,  0.02831365,  0.0192212 ,
              0.02130797,  0.02704695,  0.01245533,  0.01169101, -0.09080322,
             -0.07460943, -0.06640577, -0.0711108 , -0.0800206 , -0.08184703,
             -0.08223263, -0.08530407, -0.07513322, -0.06130615, -0.05115678,
             -0.06167197, -0.07565701, -0.03062162, -0.05399513, -0.06172064,
             -0.04699902, -0.04161728, -0.12667465, -0.13412245, -0.1240728 ,
             -0.12363627, -0.15680178, -0.12218678, -0.12267543, -0.10501408,
             -0.12226037, -0.08746229, -0.08743852, -0.08831494, -0.10726064,
             -0.08244924, -0.08900497, -0.06334236, -0.05743911, -0.08110549,
             -0.08125708, -0.08365067, -0.08195527,  0.13781762,  0.09890313,
              0.09890313,  0.13914227,  0.1721361 ,  0.17259187,  0.17084116,
              0.17120174,  0.19648875,  0.17021173,  0.19716291,  0.21349457,
              0.21695487,  0.1920787 ,  0.18741268,  0.21709567,  0.21024755,
              0.27574775,  0.2937461 ,  0.28812113,  0.28942567,  0.27283022,
              0.26770025,  0.2481234 ,  0.26209718,  0.2726033 ,  0.24972846,
              0.24944334,  0.2722226 ,  0.25843644,  0.1921287 ,  0.18100646,
              0.19108912,  0.18962568,  0.18591133,  0.1918807 ,  0.19201142,
              0.16736348,  0.17053531,  0.14174297, -0.09541775, -0.12888747,
             -0.12896653, -0.11827921, -0.12787825, -0.12573926, -0.14502336,
             -0.12925714, -0.13146389], dtype=float32),
      'LightGBM': array([-0.11364861, -0.10753708, -0.11766616, -0.11223395, -0.11412605,
             -0.10862846, -0.112504  , -0.06449009, -0.08980408, -0.08267753,
             -0.11509058, -0.10639627, -0.10594004, -0.06956702,  0.13284156,
              0.13888552,  0.16208393, -0.11178089, -0.11538527, -0.11581311,
             -0.11723946, -0.06591751, -0.05626263, -0.06213337, -0.10616349,
             -0.10611073, -0.1120595 , -0.10755755, -0.10428932, -0.09894864,
             -0.05988669, -0.05359851, -0.10272266, -0.05247842, -0.0594271 ,
             -0.05760293, -0.06052661, -0.06696845, -0.07631332,  0.0422793 ,
              0.03529002, -0.00881464,  0.03737435,  0.03873912,  0.03719833,
              0.0336544 , -0.00807602, -0.01557023, -0.0056291 ,  0.03958649,
              0.03738573, -0.01222177, -0.00768875, -0.01143234, -0.00975086,
             -0.01137917, -0.00719832, -0.00886684, -0.00625407,  0.00436982,
             -0.00337146, -0.00576792,  0.00141803,  0.00396318, -0.00329252,
             -0.00340941, -0.01445077, -0.00950015, -0.00618886, -0.01479311,
             -0.00815891, -0.0376284 , -0.04453067, -0.04254921, -0.0694508 ,
             -0.03937585, -0.04536456, -0.08060603, -0.06035621, -0.02399013,
             -0.01850075, -0.06485793, -0.03231694, -0.02888327, -0.0314414 ,
             -0.07001008, -0.0452695 , -0.05103165, -0.05390383, -0.05746421,
             -0.03797466, -0.03502163, -0.00536997, -0.01379513, -0.00768614,
             -0.01065646, -0.03897131, -0.06543528, -0.07072161, -0.07615774,
             -0.04376043, -0.05890416, -0.01679975, -0.03965783, -0.04049669,
             -0.004636  , -0.04119961, -0.03319566, -0.00281297,  0.00307195,
              0.0363595 ,  0.01459706,  0.03221369,  0.0705102 ,  0.0712855 ,
              0.04708361, -0.00684605, -0.01826518, -0.01561172, -0.01806552,
             -0.03270051, -0.04529344, -0.00781891,  0.06524204,  0.06321936,
             -0.01573209,  0.01575241, -0.014934  , -0.01783161, -0.02532808,
             -0.02562017, -0.04333192, -0.00701099, -0.01193243,  0.01703452,
              0.05825468,  0.01112337,  0.02250233,  0.03747048,  0.01699262,
              0.01359073,  0.01676045,  0.02818124,  0.00563226,  0.00340208,
             -0.0031479 , -0.02708699,  0.04282108,  0.02601508,  0.0495073 ,
              0.05391516,  0.05503254,  0.04524675,  0.02929316,  0.04504682,
              0.0594422 ,  0.04994559,  0.03713755,  0.03916077,  0.02134152,
              0.05476905,  0.05199121,  0.03840635,  0.03911644, -0.06329898,
             -0.07808509, -0.09618206, -0.04916041, -0.08793618, -0.07851366,
             -0.07738071, -0.07742794, -0.07992991, -0.0319827 , -0.03149557,
             -0.04282027, -0.07667891, -0.01967181, -0.02100068,  0.00297513,
              0.01312734, -0.00301612, -0.11562777, -0.12757438, -0.12947098,
             -0.12915402, -0.14808633, -0.11576911, -0.11967896, -0.08033195,
             -0.08254971, -0.06497401, -0.08280327, -0.08233926, -0.08082849,
             -0.08146332, -0.08512282, -0.08367895, -0.0808784 , -0.07037725,
             -0.06950243, -0.07468344, -0.07236379,  0.17436957, -0.08182806,
             -0.08235553, -0.07699429,  0.17829467,  0.16061646,  0.16481334,
              0.16217687,  0.16305211,  0.15859881,  0.18679836,  0.24791195,
              0.27118699,  0.27758726,  0.17553823,  0.26757378,  0.3293054 ,
              0.32973255,  0.35666478,  0.34795625,  0.35474265,  0.33855717,
              0.33684142,  0.32169986,  0.3080117 ,  0.31295159,  0.31964337,
              0.32271945,  0.33395549,  0.26017653,  0.20620198,  0.18130836,
              0.17263479,  0.16952578,  0.17314556,  0.18493145,  0.17121742,
              0.17422633,  0.17761309, -0.07628559, -0.08386511, -0.08994979,
             -0.08747939, -0.08059805, -0.08691704, -0.07854029, -0.08880449,
             -0.08015297, -0.08736772]),
      'RandomForest': array([-0.03903663, -0.05257987, -0.06226094, -0.05685587, -0.04632466,
             -0.05537866, -0.07890739, -0.08078498, -0.08100253, -0.08939877,
             -0.09058278, -0.09218802, -0.07861904, -0.0635901 ,  0.10837612,
              0.09597047,  0.1037532 , -0.07883598, -0.08016769, -0.07578283,
             -0.0689794 , -0.06053993, -0.05819959, -0.0506293 , -0.07398174,
             -0.07325825, -0.07333677, -0.073364  , -0.080681  , -0.06832696,
             -0.06024587, -0.04829339, -0.0726629 , -0.03957931, -0.04776309,
             -0.04834891, -0.04694406, -0.06221525, -0.06532274, -0.06389339,
             -0.066269  , -0.08397891, -0.06589778, -0.06381755, -0.06794663,
             -0.07480193, -0.08812511, -0.08810525, -0.08010892, -0.06673067,
             -0.06622756, -0.08052962, -0.09027876, -0.08984126, -0.09124579,
             -0.09172985, -0.07070931, -0.07237978, -0.07211713, -0.07314499,
             -0.07089484, -0.07080404, -0.0733401 , -0.06737592, -0.0649543 ,
             -0.07295698, -0.07246025, -0.07367709, -0.07330918, -0.07303109,
             -0.07127837, -0.07783718, -0.07762411, -0.08666929, -0.08991044,
             -0.08547182, -0.09058814, -0.09923845, -0.1054309 , -0.10841808,
             -0.09922969, -0.10145381, -0.10105092, -0.1075232 , -0.11341934,
             -0.09981887, -0.09990441, -0.08485867, -0.08314349, -0.08289449,
             -0.07223732, -0.06657552, -0.06744746, -0.0671481 , -0.06584826,
             -0.06748147, -0.06962342, -0.09899115, -0.10513107, -0.09980075,
             -0.10498384, -0.07339817, -0.07660862, -0.06333034, -0.06390655,
             -0.06338254, -0.05359963, -0.04628743, -0.0301078 , -0.03774633,
             -0.03836455, -0.05906303, -0.04918432, -0.03895009, -0.03557773,
             -0.03943026, -0.04692614, -0.04810456, -0.05293428, -0.05382544,
             -0.04776978, -0.06340516, -0.04442591, -0.03697668, -0.02165721,
             -0.04853491, -0.04669217, -0.03929338, -0.05191389, -0.05020408,
             -0.04992878, -0.06862506, -0.06900324, -0.06767974, -0.0365845 ,
             -0.03039627, -0.05330556, -0.05167764, -0.03973568, -0.05575126,
             -0.05576822, -0.05392426, -0.04985223, -0.05271463, -0.05234402,
             -0.05469134, -0.03046596, -0.02191653, -0.03128254, -0.02466186,
             -0.02452487, -0.02365883, -0.02616141,  0.01018931, -0.00222415,
             -0.00703238, -0.01805801, -0.01754596, -0.0172337 , -0.01959682,
             -0.02074851, -0.03014522, -0.03414083, -0.03480092, -0.11077532,
             -0.10855741, -0.09459866, -0.1046373 , -0.10791037, -0.10679347,
             -0.10910036, -0.10901798, -0.10585205, -0.10789078, -0.0995537 ,
             -0.11032275, -0.10771594, -0.05669271, -0.06126953, -0.07232584,
             -0.06675942, -0.05955783, -0.11751006, -0.11317513, -0.12090889,
             -0.11948223, -0.12643395, -0.11465936, -0.11260052, -0.08910824,
             -0.09585779, -0.06593215, -0.09536278, -0.08866945, -0.08940699,
             -0.07510985, -0.08306985, -0.07967122, -0.06844162, -0.07998724,
             -0.07968112, -0.08100446, -0.06347258,  0.09608398, -0.04393552,
             -0.00459398, -0.0006565 ,  0.09091556,  0.08590676,  0.07655899,
              0.10203166,  0.10152201,  0.102426  ,  0.10389743,  0.11231941,
              0.13989251,  0.12722801,  0.09975981,  0.12590981,  0.13343697,
              0.1724114 ,  0.21910705,  0.19500099,  0.20371264,  0.20346054,
              0.17265951,  0.15933282,  0.16383067,  0.17330288,  0.17029131,
              0.16245418,  0.178797  ,  0.12641472,  0.11124738,  0.07556096,
              0.08127456,  0.08383081,  0.08576951,  0.06676322,  0.06378817,
              0.04750626,  0.03708094, -0.0390135 , -0.1114845 , -0.10495619,
             -0.10777412, -0.10292151, -0.10427882, -0.10414556, -0.10470522,
             -0.1039866 , -0.10657493])},
     'actual': array([ 0.02394792,  0.03881676,  0.03050572,  0.01949552,  0.02928214,
            -0.02573932, -0.02445282, -0.00731964, -0.00423502, -0.00831134,
             0.01850657,  0.05078024,  0.05848893,  0.07596527,  0.07354431,
             0.04676189,  0.02949346, -0.01004314,  0.00219762,  0.01664606,
             0.03792559,  0.05878046,  0.05642036,  0.04036824,  0.02509598,
            -0.03631966, -0.04079295, -0.04921531, -0.03325113, -0.01989417,
            -0.02601859, -0.02922968, -0.00551453,  0.01571822,  0.03045088,
             0.03903974,  0.05749934,  0.06637933,  0.07346664,  0.07269795,
             0.0546509 ,  0.06714185,  0.08881678,  0.1042512 ,  0.09086347,
             0.0565173 ,  0.05937291,  0.08382858,  0.13279663,  0.14354391,
             0.13084651,  0.12319176,  0.15065218,  0.15992849,  0.15335775,
             0.11974931,  0.16198515,  0.15625519,  0.22130931,  0.22900052,
             0.22080816,  0.20600153,  0.21646425,  0.25639982,  0.25138025,
             0.24290513,  0.21010606,  0.20221556,  0.21060895,  0.19881087,
             0.1547069 ,  0.17606048,  0.16771595,  0.16030372,  0.17408131,
             0.14199985,  0.17685973,  0.09765476,  0.06505946,  0.07919744,
             0.07873713,  0.08602622,  0.07241319,  0.07045954,  0.12810748,
             0.13188484,  0.14617446,  0.15548701,  0.1501816 ,  0.1670343 ,
             0.1731048 ,  0.19808507,  0.20072019,  0.19046118,  0.15300474,
             0.15028758,  0.08756614,  0.10688085,  0.12924211,  0.12299323,
             0.06053625,  0.05207778,  0.03949926,  0.03515452,  0.05187409,
             0.07308307,  0.08241737,  0.10019179,  0.10485746,  0.09278842,
             0.07472127,  0.0665921 ,  0.10742456,  0.1012899 ,  0.09130885,
             0.08258727,  0.06576237,  0.04412301,  0.06157229,  0.07455475,
             0.07038563,  0.10724731,  0.15354612,  0.13920186,  0.11059256,
             0.12230262,  0.09840089,  0.06784934,  0.07968196,  0.08528863,
             0.05356883,  0.04241156,  0.05547122,  0.07024013,  0.07854832,
             0.03553735,  0.03785561,  0.07474408,  0.05866145,  0.05295909,
             0.02606362,  0.03653391,  0.04904108,  0.03469206,  0.05689006,
             0.08256721,  0.08956048,  0.07845009,  0.09610708,  0.13131009,
             0.1383115 ,  0.14303799,  0.16667633,  0.16720364,  0.16330709,
             0.17443261,  0.164653  ,  0.15839399,  0.15890021,  0.16051005,
             0.16135408,  0.14561694,  0.13720511,  0.12963742,  0.11709984,
             0.15328196,  0.13459628,  0.12855339,  0.13633552,  0.14430216,
             0.14575734,  0.12840458,  0.14801651,  0.16456567,  0.15650632,
             0.15419602,  0.2200097 ,  0.20570392,  0.20580523,  0.21178689,
             0.18934587,  0.15754281,  0.15674056,  0.1375011 ,  0.15234069,
             0.15714224,  0.18162812,  0.23604618,  0.24638518,  0.23363527,
             0.25199963,  0.21119875,  0.21353146,  0.18640278,  0.22451302,
             0.24363838,  0.26670498,  0.29628364,  0.26723872,  0.30327418,
             0.37668059,  0.40864936,  0.47010768,  0.440173  ,  0.43994671,
             0.42182061,  0.41248243,  0.41017965,  0.40375965,  0.40367509,
             0.40332073,  0.38515531,  0.42399982,  0.45236046,  0.52627739,
             0.53647183,  0.48790826,  0.53716563,  0.54635753,  0.50610418,
             0.56087433,  0.5671853 ,  0.56705603,  0.52979521,  0.499438  ,
             0.46580576,  0.45260032,  0.44874873,  0.45219378,  0.44150576,
             0.43753792,  0.43907134,  0.42297666,  0.38886164,  0.41517074,
             0.4029924 ,  0.4082984 ,  0.45308766,  0.46307912,  0.42025064,
             0.43154222,  0.41977874,  0.41419989,  0.39234716,  0.36035339,
             0.40569758,  0.43601177,  0.44987182,  0.41046424,  0.42572843,
             0.3822146 ,  0.36166168]),
     'test_dates': array(['2011-02-07T00:00:00.000000', '2011-02-08T00:00:00.000000',
            '2011-02-09T00:00:00.000000', '2011-02-10T00:00:00.000000',
            '2011-02-11T00:00:00.000000', '2011-02-14T00:00:00.000000',
            '2011-02-15T00:00:00.000000', '2011-02-16T00:00:00.000000',
            '2011-02-17T00:00:00.000000', '2011-02-18T00:00:00.000000',
            '2011-02-21T00:00:00.000000', '2011-02-22T00:00:00.000000',
            '2011-02-23T00:00:00.000000', '2011-02-24T00:00:00.000000',
            '2011-02-25T00:00:00.000000', '2011-02-28T00:00:00.000000',
            '2011-03-01T00:00:00.000000', '2011-03-03T00:00:00.000000',
            '2011-03-04T00:00:00.000000', '2011-03-07T00:00:00.000000',
            '2011-03-08T00:00:00.000000', '2011-03-09T00:00:00.000000',
            '2011-03-10T00:00:00.000000', '2011-03-11T00:00:00.000000',
            '2011-03-14T00:00:00.000000', '2011-03-15T00:00:00.000000',
            '2011-03-16T00:00:00.000000', '2011-03-17T00:00:00.000000',
            '2011-03-18T00:00:00.000000', '2011-03-21T00:00:00.000000',
            '2011-03-22T00:00:00.000000', '2011-03-23T00:00:00.000000',
            '2011-03-24T00:00:00.000000', '2011-03-25T00:00:00.000000',
            '2011-03-28T00:00:00.000000', '2011-03-29T00:00:00.000000',
            '2011-03-30T00:00:00.000000', '2011-03-31T00:00:00.000000',
            '2011-04-01T00:00:00.000000', '2011-04-04T00:00:00.000000',
            '2011-04-05T00:00:00.000000', '2011-04-06T00:00:00.000000',
            '2011-04-07T00:00:00.000000', '2011-04-08T00:00:00.000000',
            '2011-04-11T00:00:00.000000', '2011-04-13T00:00:00.000000',
            '2011-04-15T00:00:00.000000', '2011-04-18T00:00:00.000000',
            '2011-04-19T00:00:00.000000', '2011-04-20T00:00:00.000000',
            '2011-04-21T00:00:00.000000', '2011-04-25T00:00:00.000000',
            '2011-04-26T00:00:00.000000', '2011-04-27T00:00:00.000000',
            '2011-04-28T00:00:00.000000', '2011-04-29T00:00:00.000000',
            '2011-05-02T00:00:00.000000', '2011-05-03T00:00:00.000000',
            '2011-05-04T00:00:00.000000', '2011-05-05T00:00:00.000000',
            '2011-05-06T00:00:00.000000', '2011-05-09T00:00:00.000000',
            '2011-05-10T00:00:00.000000', '2011-05-11T00:00:00.000000',
            '2011-05-12T00:00:00.000000', '2011-05-13T00:00:00.000000',
            '2011-05-16T00:00:00.000000', '2011-05-17T00:00:00.000000',
            '2011-05-18T00:00:00.000000', '2011-05-19T00:00:00.000000',
            '2011-05-20T00:00:00.000000', '2011-05-23T00:00:00.000000',
            '2011-05-24T00:00:00.000000', '2011-05-25T00:00:00.000000',
            '2011-05-26T00:00:00.000000', '2011-05-27T00:00:00.000000',
            '2011-05-30T00:00:00.000000', '2011-05-31T00:00:00.000000',
            '2011-06-01T00:00:00.000000', '2011-06-02T00:00:00.000000',
            '2011-06-03T00:00:00.000000', '2011-06-06T00:00:00.000000',
            '2011-06-07T00:00:00.000000', '2011-06-08T00:00:00.000000',
            '2011-06-09T00:00:00.000000', '2011-06-10T00:00:00.000000',
            '2011-06-13T00:00:00.000000', '2011-06-14T00:00:00.000000',
            '2011-06-15T00:00:00.000000', '2011-06-16T00:00:00.000000',
            '2011-06-17T00:00:00.000000', '2011-06-20T00:00:00.000000',
            '2011-06-21T00:00:00.000000', '2011-06-22T00:00:00.000000',

In [13]:
backtest_results

{'ASIAN PAINTS LTD.': {'1Y': {'cv_hit': np.float64(0.7460317460317459),
   'cv_rmse': np.float64(0.21571250946461554),
   'cv_r2': np.float64(-4.989096057065817),
   'cv_hit_std': np.float64(0.28757786620253056),
   'mean_hits': {'XGBoost': np.float64(0.6932234432234432),
    'LightGBM': np.float64(0.7509157509157508),
    'RandomForest': np.float64(0.7155067155067154)},
   'blend_weights': {'XGBoost': np.float64(0.24812892807462716),
    'LightGBM': np.float64(0.4418063037730408),
    'RandomForest': np.float64(0.3100647681523321)},
   'fold_metrics': [{'fold': 1,
     'hits': {'XGBoost': 0.38492063492063494,
      'LightGBM': 0.376984126984127,
      'RandomForest': 0.3531746031746032},
     'ens_hit': 0.36507936507936506,
     'ens_rmse': 0.22513713597350893,
     'ens_r2': -1.1985461656366656,
     'preds': {'XGBoost': array([-0.1044765 , -0.07489797, -0.06424744, -0.06205198, -0.06330624,
             -0.06381287, -0.07357074, -0.07105547, -0.07529718, -0.07756619,
             -0.07810199, -0.07385571, -0.06268528, -0.1038496 ,  0.12167266,
              0.12129943,  0.13022092, -0.1031397 , -0.1025662 , -0.07531757,
             -0.10237852, -0.10074192, -0.09764866, -0.09178157, -0.07664663,
             -0.07874086, -0.08439672, -0.06073184, -0.06864684, -0.05983721,
             -0.0578994 , -0.05051345, -0.05760656, -0.07322124, -0.06419297,
             -0.04958172, -0.08476066, -0.09334514, -0.06924706,  0.00816531,
             -0.02849077, -0.0196884 , -0.01411537,  0.00313788, -0.00143055,
             -0.00896924, -0.01648387, -0.03721721, -0.02588501, -0.01460617,
             -0.01363939, -0.0156915 , -0.01091216, -0.03339109, -0.0265106 ,
             -0.01081111, -0.01402787, -0.01330805, -0.01556916, -0.0100854 ,
             -0.02299038, -0.0232034 , -0.01423088, -0.01244849, -0.02804156,
             -0.01389906, -0.02918332, -0.01329324, -0.01495901, -0.01902544,
             -0.01623368, -0.02773543, -0.03013776, -0.04245425, -0.04385426,
             -0.03981364, -0.04564346, -0.05634929, -0.0527474 , -0.06564738,
             -0.05010387, -0.06075988, -0.05418629, -0.07537879, -0.0779385 ,
             -0.06337774, -0.06361679, -0.04578225, -0.04637067, -0.04801538,
             -0.04428135, -0.03105282, -0.02125242, -0.02781472, -0.02650659,
             -0.02065559, -0.03616078, -0.06063149, -0.06776186, -0.07163674,
             -0.06650923, -0.05798222, -0.05153228, -0.03463379, -0.0370312 ,
             -0.02954924, -0.02682328, -0.02359156, -0.00693526, -0.01025418,
             -0.01298856, -0.01604853, -0.00580218,  0.00307871,  0.00743984,
              0.00444459, -0.06592643, -0.06329737, -0.06885438, -0.06690245,
             -0.0745628 , -0.07706792, -0.04739982, -0.05672041,  0.02452358,
             -0.05651796, -0.05134999, -0.05878088, -0.06897677, -0.06647912,
             -0.06567704, -0.08655463, -0.08616123, -0.08425773, -0.00741958,
              0.00468295, -0.01873589, -0.0151379 , -0.0031858 , -0.02028773,
             -0.02345731, -0.01749655, -0.01549963, -0.0220436 , -0.02113157,
             -0.02417016, -0.00457679,  0.01486855,  0.01031099,  0.02411479,
              0.03409494,  0.03493677,  0.02002405,  0.06875205,  0.02572646,
              0.05845865,  0.05413909,  0.02414137,  0.02831365,  0.0192212 ,
              0.02130797,  0.02704695,  0.01245533,  0.01169101, -0.09080322,
             -0.07460943, -0.06640577, -0.0711108 , -0.0800206 , -0.08184703,
             -0.08223263, -0.08530407, -0.07513322, -0.06130615, -0.05115678,
             -0.06167197, -0.07565701, -0.03062162, -0.05399513, -0.06172064,
             -0.04699902, -0.04161728, -0.12667465, -0.13412245, -0.1240728 ,
             -0.12363627, -0.15680178, -0.12218678, -0.12267543, -0.10501408,
             -0.12226037, -0.08746229, -0.08743852, -0.08831494, -0.10726064,
             -0.08244924, -0.08900497, -0.06334236, -0.05743911, -0.08110549,
             -0.08125708, -0.08365067, -0.08195527,  0.13781762,  0.09890313,
              0.09890313,  0.13914227,  0.1721361 ,  0.17259187,  0.17084116,
              0.17120174,  0.19648875,  0.17021173,  0.19716291,  0.21349457,
              0.21695487,  0.1920787 ,  0.18741268,  0.21709567,  0.21024755,
              0.27574775,  0.2937461 ,  0.28812113,  0.28942567,  0.27283022,
              0.26770025,  0.2481234 ,  0.26209718,  0.2726033 ,  0.24972846,
              0.24944334,  0.2722226 ,  0.25843644,  0.1921287 ,  0.18100646,
              0.19108912,  0.18962568,  0.18591133,  0.1918807 ,  0.19201142,
              0.16736348,  0.17053531,  0.14174297, -0.09541775, -0.12888747,
             -0.12896653, -0.11827921, -0.12787825, -0.12573926, -0.14502336,
             -0.12925714, -0.13146389], dtype=float32),
      'LightGBM': array([-0.11364861, -0.10753708, -0.11766616, -0.11223395, -0.11412605,
             -0.10862846, -0.112504  , -0.06449009, -0.08980408, -0.08267753,
             -0.11509058, -0.10639627, -0.10594004, -0.06956702,  0.13284156,
              0.13888552,  0.16208393, -0.11178089, -0.11538527, -0.11581311,
             -0.11723946, -0.06591751, -0.05626263, -0.06213337, -0.10616349,
             -0.10611073, -0.1120595 , -0.10755755, -0.10428932, -0.09894864,
             -0.05988669, -0.05359851, -0.10272266, -0.05247842, -0.0594271 ,
             -0.05760293, -0.06052661, -0.06696845, -0.07631332,  0.0422793 ,
              0.03529002, -0.00881464,  0.03737435,  0.03873912,  0.03719833,
              0.0336544 , -0.00807602, -0.01557023, -0.0056291 ,  0.03958649,
              0.03738573, -0.01222177, -0.00768875, -0.01143234, -0.00975086,
             -0.01137917, -0.00719832, -0.00886684, -0.00625407,  0.00436982,
             -0.00337146, -0.00576792,  0.00141803,  0.00396318, -0.00329252,
             -0.00340941, -0.01445077, -0.00950015, -0.00618886, -0.01479311,
             -0.00815891, -0.0376284 , -0.04453067, -0.04254921, -0.0694508 ,
             -0.03937585, -0.04536456, -0.08060603, -0.06035621, -0.02399013,
             -0.01850075, -0.06485793, -0.03231694, -0.02888327, -0.0314414 ,
             -0.07001008, -0.0452695 , -0.05103165, -0.05390383, -0.05746421,
             -0.03797466, -0.03502163, -0.00536997, -0.01379513, -0.00768614,
             -0.01065646, -0.03897131, -0.06543528, -0.07072161, -0.07615774,
             -0.04376043, -0.05890416, -0.01679975, -0.03965783, -0.04049669,
             -0.004636  , -0.04119961, -0.03319566, -0.00281297,  0.00307195,
              0.0363595 ,  0.01459706,  0.03221369,  0.0705102 ,  0.0712855 ,
              0.04708361, -0.00684605, -0.01826518, -0.01561172, -0.01806552,
             -0.03270051, -0.04529344, -0.00781891,  0.06524204,  0.06321936,
             -0.01573209,  0.01575241, -0.014934  , -0.01783161, -0.02532808,
             -0.02562017, -0.04333192, -0.00701099, -0.01193243,  0.01703452,
              0.05825468,  0.01112337,  0.02250233,  0.03747048,  0.01699262,
              0.01359073,  0.01676045,  0.02818124,  0.00563226,  0.00340208,
             -0.0031479 , -0.02708699,  0.04282108,  0.02601508,  0.0495073 ,
              0.05391516,  0.05503254,  0.04524675,  0.02929316,  0.04504682,
              0.0594422 ,  0.04994559,  0.03713755,  0.03916077,  0.02134152,
              0.05476905,  0.05199121,  0.03840635,  0.03911644, -0.06329898,
             -0.07808509, -0.09618206, -0.04916041, -0.08793618, -0.07851366,
             -0.07738071, -0.07742794, -0.07992991, -0.0319827 , -0.03149557,
             -0.04282027, -0.07667891, -0.01967181, -0.02100068,  0.00297513,
              0.01312734, -0.00301612, -0.11562777, -0.12757438, -0.12947098,
             -0.12915402, -0.14808633, -0.11576911, -0.11967896, -0.08033195,
             -0.08254971, -0.06497401, -0.08280327, -0.08233926, -0.08082849,
             -0.08146332, -0.08512282, -0.08367895, -0.0808784 , -0.07037725,
             -0.06950243, -0.07468344, -0.07236379,  0.17436957, -0.08182806,
             -0.08235553, -0.07699429,  0.17829467,  0.16061646,  0.16481334,
              0.16217687,  0.16305211,  0.15859881,  0.18679836,  0.24791195,
              0.27118699,  0.27758726,  0.17553823,  0.26757378,  0.3293054 ,
              0.32973255,  0.35666478,  0.34795625,  0.35474265,  0.33855717,
              0.33684142,  0.32169986,  0.3080117 ,  0.31295159,  0.31964337,
              0.32271945,  0.33395549,  0.26017653,  0.20620198,  0.18130836,
              0.17263479,  0.16952578,  0.17314556,  0.18493145,  0.17121742,
              0.17422633,  0.17761309, -0.07628559, -0.08386511, -0.08994979,
             -0.08747939, -0.08059805, -0.08691704, -0.07854029, -0.08880449,
             -0.08015297, -0.08736772]),
      'RandomForest': array([-0.03903663, -0.05257987, -0.06226094, -0.05685587, -0.04632466,
             -0.05537866, -0.07890739, -0.08078498, -0.08100253, -0.08939877,
             -0.09058278, -0.09218802, -0.07861904, -0.0635901 ,  0.10837612,
              0.09597047,  0.1037532 , -0.07883598, -0.08016769, -0.07578283,
             -0.0689794 , -0.06053993, -0.05819959, -0.0506293 , -0.07398174,
             -0.07325825, -0.07333677, -0.073364  , -0.080681  , -0.06832696,
             -0.06024587, -0.04829339, -0.0726629 , -0.03957931, -0.04776309,
             -0.04834891, -0.04694406, -0.06221525, -0.06532274, -0.06389339,
             -0.066269  , -0.08397891, -0.06589778, -0.06381755, -0.06794663,
             -0.07480193, -0.08812511, -0.08810525, -0.08010892, -0.06673067,
             -0.06622756, -0.08052962, -0.09027876, -0.08984126, -0.09124579,
             -0.09172985, -0.07070931, -0.07237978, -0.07211713, -0.07314499,
             -0.07089484, -0.07080404, -0.0733401 , -0.06737592, -0.0649543 ,
             -0.07295698, -0.07246025, -0.07367709, -0.07330918, -0.07303109,
             -0.07127837, -0.07783718, -0.07762411, -0.08666929, -0.08991044,
             -0.08547182, -0.09058814, -0.09923845, -0.1054309 , -0.10841808,
             -0.09922969, -0.10145381, -0.10105092, -0.1075232 , -0.11341934,
             -0.09981887, -0.09990441, -0.08485867, -0.08314349, -0.08289449,
             -0.07223732, -0.06657552, -0.06744746, -0.0671481 , -0.06584826,
             -0.06748147, -0.06962342, -0.09899115, -0.10513107, -0.09980075,
             -0.10498384, -0.07339817, -0.07660862, -0.06333034, -0.06390655,
             -0.06338254, -0.05359963, -0.04628743, -0.0301078 , -0.03774633,
             -0.03836455, -0.05906303, -0.04918432, -0.03895009, -0.03557773,
             -0.03943026, -0.04692614, -0.04810456, -0.05293428, -0.05382544,
             -0.04776978, -0.06340516, -0.04442591, -0.03697668, -0.02165721,
             -0.04853491, -0.04669217, -0.03929338, -0.05191389, -0.05020408,
             -0.04992878, -0.06862506, -0.06900324, -0.06767974, -0.0365845 ,
             -0.03039627, -0.05330556, -0.05167764, -0.03973568, -0.05575126,
             -0.05576822, -0.05392426, -0.04985223, -0.05271463, -0.05234402,
             -0.05469134, -0.03046596, -0.02191653, -0.03128254, -0.02466186,
             -0.02452487, -0.02365883, -0.02616141,  0.01018931, -0.00222415,
             -0.00703238, -0.01805801, -0.01754596, -0.0172337 , -0.01959682,
             -0.02074851, -0.03014522, -0.03414083, -0.03480092, -0.11077532,
             -0.10855741, -0.09459866, -0.1046373 , -0.10791037, -0.10679347,
             -0.10910036, -0.10901798, -0.10585205, -0.10789078, -0.0995537 ,
             -0.11032275, -0.10771594, -0.05669271, -0.06126953, -0.07232584,
             -0.06675942, -0.05955783, -0.11751006, -0.11317513, -0.12090889,
             -0.11948223, -0.12643395, -0.11465936, -0.11260052, -0.08910824,
             -0.09585779, -0.06593215, -0.09536278, -0.08866945, -0.08940699,
             -0.07510985, -0.08306985, -0.07967122, -0.06844162, -0.07998724,
             -0.07968112, -0.08100446, -0.06347258,  0.09608398, -0.04393552,
             -0.00459398, -0.0006565 ,  0.09091556,  0.08590676,  0.07655899,
              0.10203166,  0.10152201,  0.102426  ,  0.10389743,  0.11231941,
              0.13989251,  0.12722801,  0.09975981,  0.12590981,  0.13343697,
              0.1724114 ,  0.21910705,  0.19500099,  0.20371264,  0.20346054,
              0.17265951,  0.15933282,  0.16383067,  0.17330288,  0.17029131,
              0.16245418,  0.178797  ,  0.12641472,  0.11124738,  0.07556096,
              0.08127456,  0.08383081,  0.08576951,  0.06676322,  0.06378817,
              0.04750626,  0.03708094, -0.0390135 , -0.1114845 , -0.10495619,
             -0.10777412, -0.10292151, -0.10427882, -0.10414556, -0.10470522,
             -0.1039866 , -0.10657493])},
     'actual': array([ 0.02394792,  0.03881676,  0.03050572,  0.01949552,  0.02928214,
            -0.02573932, -0.02445282, -0.00731964, -0.00423502, -0.00831134,
             0.01850657,  0.05078024,  0.05848893,  0.07596527,  0.07354431,
             0.04676189,  0.02949346, -0.01004314,  0.00219762,  0.01664606,
             0.03792559,  0.05878046,  0.05642036,  0.04036824,  0.02509598,
            -0.03631966, -0.04079295, -0.04921531, -0.03325113, -0.01989417,
            -0.02601859, -0.02922968, -0.00551453,  0.01571822,  0.03045088,
             0.03903974,  0.05749934,  0.06637933,  0.07346664,  0.07269795,
             0.0546509 ,  0.06714185,  0.08881678,  0.1042512 ,  0.09086347,
             0.0565173 ,  0.05937291,  0.08382858,  0.13279663,  0.14354391,
             0.13084651,  0.12319176,  0.15065218,  0.15992849,  0.15335775,
             0.11974931,  0.16198515,  0.15625519,  0.22130931,  0.22900052,
             0.22080816,  0.20600153,  0.21646425,  0.25639982,  0.25138025,
             0.24290513,  0.21010606,  0.20221556,  0.21060895,  0.19881087,
             0.1547069 ,  0.17606048,  0.16771595,  0.16030372,  0.17408131,
             0.14199985,  0.17685973,  0.09765476,  0.06505946,  0.07919744,
             0.07873713,  0.08602622,  0.07241319,  0.07045954,  0.12810748,
             0.13188484,  0.14617446,  0.15548701,  0.1501816 ,  0.1670343 ,
             0.1731048 ,  0.19808507,  0.20072019,  0.19046118,  0.15300474,
             0.15028758,  0.08756614,  0.10688085,  0.12924211,  0.12299323,
             0.06053625,  0.05207778,  0.03949926,  0.03515452,  0.05187409,
             0.07308307,  0.08241737,  0.10019179,  0.10485746,  0.09278842,
             0.07472127,  0.0665921 ,  0.10742456,  0.1012899 ,  0.09130885,
             0.08258727,  0.06576237,  0.04412301,  0.06157229,  0.07455475,
             0.07038563,  0.10724731,  0.15354612,  0.13920186,  0.11059256,
             0.12230262,  0.09840089,  0.06784934,  0.07968196,  0.08528863,
             0.05356883,  0.04241156,  0.05547122,  0.07024013,  0.07854832,
             0.03553735,  0.03785561,  0.07474408,  0.05866145,  0.05295909,
             0.02606362,  0.03653391,  0.04904108,  0.03469206,  0.05689006,
             0.08256721,  0.08956048,  0.07845009,  0.09610708,  0.13131009,
             0.1383115 ,  0.14303799,  0.16667633,  0.16720364,  0.16330709,
             0.17443261,  0.164653  ,  0.15839399,  0.15890021,  0.16051005,
             0.16135408,  0.14561694,  0.13720511,  0.12963742,  0.11709984,
             0.15328196,  0.13459628,  0.12855339,  0.13633552,  0.14430216,
             0.14575734,  0.12840458,  0.14801651,  0.16456567,  0.15650632,
             0.15419602,  0.2200097 ,  0.20570392,  0.20580523,  0.21178689,
             0.18934587,  0.15754281,  0.15674056,  0.1375011 ,  0.15234069,
             0.15714224,  0.18162812,  0.23604618,  0.24638518,  0.23363527,
             0.25199963,  0.21119875,  0.21353146,  0.18640278,  0.22451302,
             0.24363838,  0.26670498,  0.29628364,  0.26723872,  0.30327418,
             0.37668059,  0.40864936,  0.47010768,  0.440173  ,  0.43994671,
             0.42182061,  0.41248243,  0.41017965,  0.40375965,  0.40367509,
             0.40332073,  0.38515531,  0.42399982,  0.45236046,  0.52627739,
             0.53647183,  0.48790826,  0.53716563,  0.54635753,  0.50610418,
             0.56087433,  0.5671853 ,  0.56705603,  0.52979521,  0.499438  ,
             0.46580576,  0.45260032,  0.44874873,  0.45219378,  0.44150576,
             0.43753792,  0.43907134,  0.42297666,  0.38886164,  0.41517074,
             0.4029924 ,  0.4082984 ,  0.45308766,  0.46307912,  0.42025064,
             0.43154222,  0.41977874,  0.41419989,  0.39234716,  0.36035339,
             0.40569758,  0.43601177,  0.44987182,  0.41046424,  0.42572843,
             0.3822146 ,  0.36166168]),
     'test_dates': array(['2011-02-07T00:00:00.000000', '2011-02-08T00:00:00.000000',
            '2011-02-09T00:00:00.000000', '2011-02-10T00:00:00.000000',
            '2011-02-11T00:00:00.000000', '2011-02-14T00:00:00.000000',
            '2011-02-15T00:00:00.000000', '2011-02-16T00:00:00.000000',
            '2011-02-17T00:00:00.000000', '2011-02-18T00:00:00.000000',
            '2011-02-21T00:00:00.000000', '2011-02-22T00:00:00.000000',
            '2011-02-23T00:00:00.000000', '2011-02-24T00:00:00.000000',
            '2011-02-25T00:00:00.000000', '2011-02-28T00:00:00.000000',
            '2011-03-01T00:00:00.000000', '2011-03-03T00:00:00.000000',
            '2011-03-04T00:00:00.000000', '2011-03-07T00:00:00.000000',
            '2011-03-08T00:00:00.000000', '2011-03-09T00:00:00.000000',
            '2011-03-10T00:00:00.000000', '2011-03-11T00:00:00.000000',
            '2011-03-14T00:00:00.000000', '2011-03-15T00:00:00.000000',
            '2011-03-16T00:00:00.000000', '2011-03-17T00:00:00.000000',
            '2011-03-18T00:00:00.000000', '2011-03-21T00:00:00.000000',
            '2011-03-22T00:00:00.000000', '2011-03-23T00:00:00.000000',
            '2011-03-24T00:00:00.000000', '2011-03-25T00:00:00.000000',
            '2011-03-28T00:00:00.000000', '2011-03-29T00:00:00.000000',
            '2011-03-30T00:00:00.000000', '2011-03-31T00:00:00.000000',
            '2011-04-01T00:00:00.000000', '2011-04-04T00:00:00.000000',
            '2011-04-05T00:00:00.000000', '2011-04-06T00:00:00.000000',
            '2011-04-07T00:00:00.000000', '2011-04-08T00:00:00.000000',
            '2011-04-11T00:00:00.000000', '2011-04-13T00:00:00.000000',
            '2011-04-15T00:00:00.000000', '2011-04-18T00:00:00.000000',
            '2011-04-19T00:00:00.000000', '2011-04-20T00:00:00.000000',
            '2011-04-21T00:00:00.000000', '2011-04-25T00:00:00.000000',
            '2011-04-26T00:00:00.000000', '2011-04-27T00:00:00.000000',
            '2011-04-28T00:00:00.000000', '2011-04-29T00:00:00.000000',
            '2011-05-02T00:00:00.000000', '2011-05-03T00:00:00.000000',
            '2011-05-04T00:00:00.000000', '2011-05-05T00:00:00.000000',
            '2011-05-06T00:00:00.000000', '2011-05-09T00:00:00.000000',
            '2011-05-10T00:00:00.000000', '2011-05-11T00:00:00.000000',
            '2011-05-12T00:00:00.000000', '2011-05-13T00:00:00.000000',
            '2011-05-16T00:00:00.000000', '2011-05-17T00:00:00.000000',
            '2011-05-18T00:00:00.000000', '2011-05-19T00:00:00.000000',
            '2011-05-20T00:00:00.000000', '2011-05-23T00:00:00.000000',
            '2011-05-24T00:00:00.000000', '2011-05-25T00:00:00.000000',
            '2011-05-26T00:00:00.000000', '2011-05-27T00:00:00.000000',
            '2011-05-30T00:00:00.000000', '2011-05-31T00:00:00.000000',
            '2011-06-01T00:00:00.000000', '2011-06-02T00:00:00.000000',
            '2011-06-03T00:00:00.000000', '2011-06-06T00:00:00.000000',
            '2011-06-07T00:00:00.000000', '2011-06-08T00:00:00.000000',
            '2011-06-09T00:00:00.000000', '2011-06-10T00:00:00.000000',
            '2011-06-13T00:00:00.000000', '2011-06-14T00:00:00.000000',
            '2011-06-15T00:00:00.000000', '2011-06-16T00:00:00.000000',
            '2011-06-17T00:00:00.000000', '2011-06-20T00:00:00.000000',
            '2011-06-21T00:00:00.000000', '2011-06-22T00:00:00.000000',

In [14]:
# ─────────────────────────────────────────────
# 8. PREDICTED RETURN RANKING  (Deliverable 1)
# ─────────────────────────────────────────────

print(f"\n{'═'*110}")
print("  PREDICTED RETURN RANKING  —  1-Year vs 3-Year Horizon (Live Inference)")
print(f"  BUY signal threshold : must beat risk-free rate of {RF_RATE:.1%} p.a.")
print(f"{'='*110}")
print(f"  {'Rank':<5} {'Company':<35} "
      f"{'1Y Pred Ann':>13} {'1Y Signal':>10} "
      f"{'3Y Pred Ann':>13} {'3Y Signal':>10} "
      f"{'Consensus':>14}")
print(f"  {'─'*100}")

ranked_1y = sorted(names_list, key=lambda n: pred_returns["1Y"].get(n, -99), reverse=True)

for rank, name in enumerate(ranked_1y, 1):
    short  = name.replace(" LTD.", "").strip()
    ret_1y = pred_returns["1Y"].get(name, float("nan"))
    ret_3y = pred_returns["3Y"].get(name, float("nan"))

    sig_1y = "BUY  ▲" if ret_1y > BUY_THRESHOLD_1Y else "SELL ▼"
    sig_3y = "BUY  ▲" if ret_3y > BUY_THRESHOLD_3Y else "SELL ▼"

    if   sig_1y == "BUY  ▲" and sig_3y == "BUY  ▲": consensus = "STRONG BUY"
    elif sig_1y == "SELL ▼" and sig_3y == "SELL ▼": consensus = "STRONG SELL"
    elif sig_1y == "BUY  ▲":                        consensus = "TACTICAL BUY"
    else:                                           consensus = "WAIT"

    print(f"  {rank:<5} {short:<35} {ret_1y:>13.2%} {sig_1y:>10} {ret_3y:>13.2%} {sig_3y:>10} {consensus:>14}")

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  PREDICTED RETURN RANKING  —  1-Year vs 3-Year Horizon (Live Inference)
  BUY signal threshold : must beat risk-free rate of 6.5% p.a.
==============================================================================================================
  Rank  Company                               1Y Pred Ann  1Y Signal   3Y Pred Ann  3Y Signal      Consensus
  ────────────────────────────────────────────────────────────────────────────────────────────────────
  1     H D F C BANK                               -0.03%     SELL ▼        -2.47%     SELL ▼    STRONG SELL
  2     ASIAN PAINTS                               -6.85%     SELL ▼       -13.74%     SELL ▼    STRONG SELL
  3     TATA CONSULTANCY SERVICES                 -15.61%     SELL ▼        -8.14%     SELL ▼    STRONG SELL
  4     ULTRATECH CEMENT                          -30.18%     SELL ▼       -20.96%     SELL ▼    STRONG SELL
  5     CIPLA                                     -34.05%     SELL ▼       -31.92%     SELL ▼    STRONG SELL
  6     I T C                                     -34.91%     SELL ▼       -25.43%     SELL ▼    STRONG SELL

In [15]:
# ─────────────────────────────────────────────
# 9. PORTFOLIO OPTIMISATION  (Max Sharpe / Cash Gate) (Deliverable 2)
# ─────────────────────────────────────────────

def run_optimisation(horizon_label, mu_raw_arr, confidence_arr, Sigma, names):
    shrinkage = np.clip((confidence_arr - 0.50) / 0.10, 0, 1)
    mu_adj    = mu_raw_arr * shrinkage
    n_total   = len(names)

    buy_mask = mu_adj > 0
    n_buy    = buy_mask.sum()

    if n_buy == 0:
        return np.zeros(n_total), RF_RATE, 0.0, 0.0, True, shrinkage, mu_adj

    elif n_buy < n_total:
        buy_idx = [i for i, b in enumerate(buy_mask) if b]
        mu_buy  = mu_adj[buy_idx]
        Sig_buy = Sigma[np.ix_(buy_idx, buy_idx)]

        def neg_sharpe_p(w):
            r_ = float(np.dot(w, mu_buy))
            v_ = float(np.sqrt(w @ Sig_buy @ w))
            return -(r_ - RF_RATE) / v_ if v_ > 0 else 0.0

        lo  = min(0.05, 1.0 / n_buy)
        opt = sco.minimize(
            neg_sharpe_p,
            np.ones(n_buy) / n_buy,
            method="SLSQP",
            bounds=[(lo, 1.0)] * n_buy,
            constraints=[{"type": "eq", "fun": lambda w: np.sum(w) - 1}],
        )
        w_out = np.zeros(n_total)
        for rank_i, idx in enumerate(buy_idx):
            w_out[idx] = opt.x[rank_i]

    else:
        def neg_sharpe_f(w):
            r_ = float(np.dot(w, mu_adj))
            v_ = float(np.sqrt(w @ Sigma @ w))
            return -(r_ - RF_RATE) / v_ if v_ > 0 else 0.0

        opt = sco.minimize(
            neg_sharpe_f,
            np.ones(n_total) / n_total,
            method="SLSQP",
            bounds=[(0.05, 0.40)] * n_total,
            constraints=[{"type": "eq", "fun": lambda w: np.sum(w) - 1}],
        )
        w_out = opt.x

    p_ret = float(np.dot(w_out, mu_adj))
    p_vol = float(np.sqrt(w_out @ Sigma @ w_out))
    shrp  = (p_ret - RF_RATE) / p_vol if p_vol > 0 else 0.0
    return w_out, p_ret, p_vol, shrp, False, shrinkage, mu_adj


# Covariance matrix
ret_df       = pd.DataFrame({n: dfs[n].set_index("date")["Return"] for n in names_list})
ret_df.index = pd.to_datetime(ret_df.index)
cov_data     = ret_df.dropna()
cov_matrix   = cov_data.cov() * 252
Sigma        = cov_matrix.values

opt_results = {}
for horizon_label in ["1Y", "3Y"]:
    mu_raw_arr     = np.array([pred_returns[horizon_label].get(n, 0.0) for n in names_list])
    confidence_arr = np.array([
        cv_summary[n][horizon_label]["cv_hit"]
        if cv_summary[n].get(horizon_label) is not None else 0.5
        for n in names_list
    ])
    w, pr, pv, sh, cash, shrink, mu_adj = run_optimisation(
        horizon_label, mu_raw_arr, confidence_arr, Sigma, names_list
    )
    opt_results[horizon_label] = {
        "weights": w, "port_ret": pr, "port_vol": pv,
        "sharpe": sh, "cash_mode": cash, "shrinkage": shrink,
        "mu_adj": mu_adj, "mu_raw": mu_raw_arr,
    }


print(f"\n{'═'*110}")
print("  BLENDED PORTFOLIO ALLOCATION  (50% Tactical 1Y  +  50% Strategic 3Y)")
print(f"{'='*110}")

w_1y        = opt_results["1Y"]["weights"]
w_3y        = opt_results["3Y"]["weights"]
w_blend_raw = 0.5 * w_1y + 0.5 * w_3y
w_blend     = w_blend_raw / w_blend_raw.sum() if w_blend_raw.sum() > 0 else w_blend_raw
CASH_MODE   = opt_results["1Y"]["cash_mode"] and opt_results["3Y"]["cash_mode"]

if CASH_MODE:
    print("  Both horizons recommend CASH — no equity allocation. Holding Risk-Free assets.")
else:
    print(f"  {'Company':<35} {'1Y Wt':>8} {'3Y Wt':>8} {'Blended Wt':>12}")
    print(f"  {SEP}")
    for i, name in enumerate(names_list):
        short = name.replace(" LTD.", "").strip()
        print(f"  {short:<35} {w_1y[i]:>8.1%} {w_3y[i]:>8.1%} {w_blend[i]:>12.1%}")

print(f"{'='*110}")

opt_weights = w_blend  # Ensure weights are passed to the backtest

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  BLENDED PORTFOLIO ALLOCATION  (50% Tactical 1Y  +  50% Strategic 3Y)
==============================================================================================================
  Both horizons recommend CASH — no equity allocation. Holding Risk-Free assets.
==============================================================================================================

In [16]:
# ─────────────────────────────────────────────
# 10. CV DIAGNOSTIC SUMMARY  (per horizon)
# ─────────────────────────────────────────────

for horizon_label in ["1Y", "3Y"]:
    print(f"\n{'═'*110}")
    print(f"  CV DIAGNOSTIC SUMMARY  —  {horizon_label} Horizon  "
          f"(ensemble mean ± std across folds)")
    print(f"{'='*110}")
    print(f"  {'Company':<35} {'XGB CV Hit':>12} {'LGB CV Hit':>12} "
          f"{'RF CV Hit':>11} {'Ens CV Hit':>12} {'Ens R²':>8} {'Stability':>10}")
    print(f"  {SEP}")

    for name in names_list:
        h = cv_summary[name].get(horizon_label)
        if h is None:
            continue
        short = name.replace(" LTD.", "").strip()
        stab  = ("High"   if h["cv_hit_std"] < 0.04 else
                 "Medium" if h["cv_hit_std"] < 0.08 else "Low")
        print(f"  {short:<35} "
              f"{h['mean_hits']['XGBoost']:>12.1%} "
              f"{h['mean_hits']['LightGBM']:>12.1%} "
              f"{h['mean_hits']['RandomForest']:>11.1%} "
              f"{h['cv_hit']:>12.1%} "
              f"{h['cv_r2']:>8.4f} "
              f"{stab:>10}")

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  CV DIAGNOSTIC SUMMARY  —  1Y Horizon  (ensemble mean ± std across folds)
==============================================================================================================
  Company                               XGB CV Hit   LGB CV Hit   RF CV Hit   Ens CV Hit   Ens R²  Stability
  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ASIAN PAINTS                               69.3%        75.1%       71.6%        74.6%  -4.9891        Low
  CIPLA                                      98.4%        98.4%       98.4%        98.4%  -4.3422     Medium
  H D F C BANK                               45.1%        44.9%       48.6%        48.4% -11.3014        Low
  I T C                                      51.1%        53.8%       61.9%        55.2% -14.4620        Low
  TATA CONSULTANCY SERVICES                  51.5%        45.8%       50.1%        46.2% -14.6477        Low
  ULTRATECH CEMENT                           55.4%        58.2%       66.8%        62.3% -12.1521        Low

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  CV DIAGNOSTIC SUMMARY  —  3Y Horizon  (ensemble mean ± std across folds)
==============================================================================================================
  Company                               XGB CV Hit   LGB CV Hit   RF CV Hit   Ens CV Hit   Ens R²  Stability
  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ASIAN PAINTS                               79.5%        80.4%       85.7%        81.5% -63.1404        Low
  CIPLA                                     100.0%       100.0%      100.0%       100.0% -12.8925       High
  H D F C BANK                               70.7%        65.2%       60.4%        67.9% -66.4656        Low
  I T C                                      84.2%        79.3%       99.6%        88.4% -867.0652        Low
  TATA CONSULTANCY SERVICES                  67.2%        64.9%       86.7%        68.6% -42.1563        Low
  ULTRATECH CEMENT                           69.9%        54.5%       44.5%        52.7% -286.8654        Low

In [17]:
# ─────────────────────────────────────────────
# 11. BLEND WEIGHT SUMMARY  (per horizon)
# ─────────────────────────────────────────────

for horizon_label in ["1Y", "3Y"]:
    print(f"\n{'═'*110}")
    print(f"  ENSEMBLE BLEND WEIGHTS  —  {horizon_label} Horizon  (CV Softmax)")
    print(f"{'='*110}")
    print(f"  {'Company':<35} {'XGBoost':>12} {'LightGBM':>12} {'RandomForest':>14}")
    print(f"  {SEP}")

    for name in names_list:
        h = cv_summary[name].get(horizon_label)
        if h is None:
            continue
        short = name.replace(" LTD.", "").strip()
        bw    = h["blend_weights"]
        print(f"  {short:<35} {bw['XGBoost']:>12.3f} {bw['LightGBM']:>12.3f} {bw['RandomForest']:>14.3f}")

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  ENSEMBLE BLEND WEIGHTS  —  1Y Horizon  (CV Softmax)
==============================================================================================================
  Company                                  XGBoost     LightGBM   RandomForest
  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ASIAN PAINTS                               0.248        0.442          0.310
  CIPLA                                      0.333        0.333          0.333
  H D F C BANK                               0.295        0.287          0.417
  I T C                                      0.190        0.248          0.561
  TATA CONSULTANCY SERVICES                  0.410        0.234          0.357
  ULTRATECH CEMENT                           0.183        0.243          0.574

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  ENSEMBLE BLEND WEIGHTS  —  3Y Horizon  (CV Softmax)
==============================================================================================================
  Company                                  XGBoost     LightGBM   RandomForest
  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ASIAN PAINTS                               0.252        0.277          0.471
  CIPLA                                      0.333        0.333          0.333
  H D F C BANK                               0.518        0.298          0.184
  I T C                                      0.159        0.097          0.744
  TATA CONSULTANCY SERVICES                  0.113        0.090          0.797
  ULTRATECH CEMENT                           0.772        0.166          0.061

In [18]:
# ─────────────────────────────────────────────
# 12. BACKTEST SUMMARY (Deliverable 3 - Expected vs Realized)
# ─────────────────────────────────────────────

for horizon_label in ["1Y", "3Y"]:
    print(f"\n{'═'*110}")
    print(f"  FINAL MODEL BACKTEST SUMMARY  —  {horizon_label} Horizon (Out-of-sample)")
    print(f"{'='*110}")
    print(f"  {'Company':<35} {'Act Ann Ret':>13} {'Hit Rate':>10} {'RMSE':>10}")
    print(f"  {SEP}")

    for name in names_list:
        h = backtest_results[name].get(horizon_label)
        if h is None or len(h.get('y_fte', [])) == 0:
            continue

        short   = name.replace(" LTD.", "").strip()
        y_fte   = h["y_fte"]
        years   = h["years"]
        act_ann = float((1 + np.mean(y_fte)) ** (1 / years) - 1)

        print(f"  {short:<35} "
              f"{act_ann:>13.2%} "
              f"{h['bt_hit']:>10.1%} "
              f"{float(np.sqrt(mean_squared_error(h['y_fte'], h['final_ens']))):>10.4f}")

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  FINAL MODEL BACKTEST SUMMARY  —  1Y Horizon (Out-of-sample)
==============================================================================================================
  Company                               Act Ann Ret   Hit Rate       RMSE
  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ASIAN PAINTS                               -7.89%      75.4%     0.1388
  CIPLA                                      -6.75%      87.7%     0.2673
  H D F C BANK                               14.89%       3.6%     0.2239
  I T C                                     -19.78%     100.0%     0.1910
  TATA CONSULTANCY SERVICES                 -16.12%     100.0%     0.1176
  ULTRATECH CEMENT                            0.28%      83.7%     0.3365

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  FINAL MODEL BACKTEST SUMMARY  —  3Y Horizon (Out-of-sample)
==============================================================================================================
  Company                               Act Ann Ret   Hit Rate       RMSE
  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────

In [19]:
# ─────────────────────────────────────────────
# 13. FEATURE IMPORTANCES  (best CV stock, both horizons)
# ─────────────────────────────────────────────
for horizon_label in ["1Y", "3Y"]:
    valid_names = [n for n in names_list if cv_summary[n].get(horizon_label) is not None]

    if not valid_names:
        continue

    best = max(valid_names, key=lambda n: cv_summary[n][horizon_label]["cv_hit"])

    print(f"\n{'═'*110}")
    print(f"  FEATURE IMPORTANCES  —  {horizon_label} Horizon  |  "
          f"{best.replace(' LTD.','').strip()}  (best CV hit rate)")
    print(f"  Short-horizon + Long-horizon + Macroeconomic features")
    print(f"  (XGBoost & LightGBM: gain-based  |  Random Forest: impurity-based)")
    print(f"{'='*110}")

    h      = backtest_results[best][horizon_label]
    fi_all = h["final_fi"]
    bw     = h["blend_weights"]

    agg_fi = {}
    for feat in FEATURES:
        agg_fi[feat] = sum(
            bw[m] * fi_all[m].get(feat, 0)
            for m in MODEL_NAMES if m in fi_all
        )

    print(f"\n  {'Rank':<6}  {'Feature':<22}  {'Type':<10}  "
          f"{'XGBoost':>10}  {'LightGBM':>10}  {'RandomForest':>13}  "
          f"{'Weighted':>10}  {'% of Total':>10}")
    print(f"  {'─'*100}")

    sorted_feats = sorted(FEATURES, key=lambda f: -agg_fi[f])
    total_fi     = sum(agg_fi.values())

    for rank, feat in enumerate(sorted_feats, 1):
        xgb_fi = fi_all.get("XGBoost",      {}).get(feat, 0)
        lgb_fi = fi_all.get("LightGBM",     {}).get(feat, 0)
        rf_fi  = fi_all.get("RandomForest", {}).get(feat, 0)
        w_fi   = agg_fi[feat]
        pct    = (w_fi / total_fi * 100) if total_fi > 0 else 0

        if   feat in MACRO_FEATURES: ftype = "Macro"
        elif feat in LONG_FEATURES:  ftype = "Long-horizon"
        else:                        ftype = "Price"

        print(f"  {rank:<6}  {feat:<22}  {ftype:<10}  "
              f"{xgb_fi:>10.4f}  {lgb_fi:>10.4f}  {rf_fi:>13.4f}  "
              f"{w_fi:>10.4f}  {pct:>9.1f}%")

    print(f"  {'─'*100}")
    print(f"  {'':<6}  {'TOTAL':<22}  {'':<10}  "
          f"{'':<10}  {'':<10}  {'':<13}  {total_fi:>10.4f}  {'100.0%':>10}")

    price_total = sum(v for f, v in agg_fi.items() if f not in MACRO_FEATURES and f not in LONG_FEATURES)
    long_total  = sum(v for f, v in agg_fi.items() if f in LONG_FEATURES)
    macro_total = sum(v for f, v in agg_fi.items() if f in MACRO_FEATURES)

    print(f"\n  Feature Group Summary:")
    print(f"  {'─'*50}")
    print(f"  {'Short-horizon Price/Volume':<35}  "
          f"{price_total:.4f}  ({price_total/total_fi*100:.1f}%)")
    print(f"  {'Long-horizon Trend/Context':<35}  "
          f"{long_total:.4f}  ({long_total/total_fi*100:.1f}%)")
    print(f"  {'Macroeconomic':<35}  "
          f"{macro_total:.4f}  ({macro_total/total_fi*100:.1f}%)")

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  FEATURE IMPORTANCES  —  1Y Horizon  |  CIPLA  (best CV hit rate)
  Short-horizon + Long-horizon + Macroeconomic features
  (XGBoost & LightGBM: gain-based  |  Random Forest: impurity-based)
==============================================================================================================

  Rank    Feature                 Type           XGBoost    LightGBM   RandomForest    Weighted  % of Total
  ────────────────────────────────────────────────────────────────────────────────────────────────────
  1       vol_252                 Long-horizon      0.0240    328.0000         0.0637    109.3626       13.0%
  2       price_vs_ma252          Long-horizon      0.0769    244.0000         0.0925     81.3898        9.7%
  3       ret_20                  Price           0.0144    217.0000         0.0109     72.3417        8.6%
  4       mom_756                 Long-horizon      0.0395    185.0000         0.1716     61.7370        7.4%
  5       mom_252                 Long-horizon      0.0108    156.0000         0.0483     52.0197        6.2%
  6       macro_inflation_qrt     Macro           0.0589    149.0000         0.0584     49.7058        5.9%
  7       vol_20                  Price           0.0097    131.0000         0.0313     43.6803        5.2%
  8       macro_gdp_qrt           Macro           0.1209    128.0000         0.0562     42.7257        5.1%
  9       price_vs_ma756          Long-horizon      0.0413    126.0000         0.1187     42.0533        5.0%
  10      vol_ratio_sr_lr         Long-horizon      0.0204    120.0000         0.0293     40.0166        4.8%
  11      mom_20                  Price           0.0102    110.0000         0.0101     36.6734        4.4%
  12      ret_5                   Price           0.0030    108.0000         0.0012     36.0014        4.3%
  13      macro_gdp_ann           Macro           0.4672     87.0000         0.1826     29.2166        3.5%
  14      mom_5                   Price           0.0019     85.0000         0.0011     28.3343        3.4%
  15      vol_5                   Price           0.0018     81.0000         0.0024     27.0014        3.2%
  16      vol_ratio               Price           0.0015     70.0000         0.0017     23.3344        2.8%
  17      price_range             Price           0.0015     64.0000         0.0017     21.3344        2.5%
  18      macro_inflation_ann     Macro           0.0699     60.0000         0.0633     20.0444        2.4%
  19      vol_ratio_252           Long-horizon      0.0254     37.0000         0.0546     12.3600        1.5%
  20      ret_1                   Price           0.0009     27.0000         0.0005      9.0005        1.1%
  ────────────────────────────────────────────────────────────────────────────────────────────────────
          TOTAL                                                                        838.3333      100.0%

  Feature Group Summary:
  ──────────────────────────────────────────────────
  Short-horizon Price/Volume           297.7019  (35.5%)
  Long-horizon Trend/Context           398.9390  (47.6%)
  Macroeconomic                        141.6924  (16.9%)

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  FEATURE IMPORTANCES  —  3Y Horizon  |  CIPLA  (best CV hit rate)
  Short-horizon + Long-horizon + Macroeconomic features
  (XGBoost & LightGBM: gain-based  |  Random Forest: impurity-based)
==============================================================================================================

  Rank    Feature                 Type           XGBoost    LightGBM   RandomForest    Weighted  % of Total
  ────────────────────────────────────────────────────────────────────────────────────────────────────
  1       vol_252                 Long-horizon      0.2005    340.0000         0.1606    113.4537       15.2%
  2       price_vs_ma252          Long-horizon      0.0264    177.0000         0.1277     59.0514        7.9%
  3       mom_756                 Long-horizon      0.0556    175.0000         0.0406     58.3654        7.8%
  4       mom_252                 Long-horizon      0.0529    167.0000         0.1258     55.7262        7.5%
  5       price_vs_ma756          Long-horizon      0.1467    166.0000         0.1346     55.4271        7.4%
  6       vol_ratio_sr_lr         Long-horizon      0.0140    161.0000         0.0131     53.6757        7.2%
  7       vol_20                  Price           0.0188    131.0000         0.0165     43.6784        5.9%
  8       macro_gdp_qrt           Macro           0.1271    129.0000         0.1372     43.0881        5.8%
  9       ret_20                  Price           0.0039    120.0000         0.0040     40.0026        5.4%
  10      mom_20                  Price           0.0015    116.0000         0.0066     38.6694        5.2%
  11      macro_inflation_qrt     Macro           0.0323    106.0000         0.0502     35.3608        4.7%
  12      ret_5                   Price           0.0021    100.0000         0.0011     33.3344        4.5%
  13      vol_5                   Price           0.0020     83.0000         0.0013     27.6678        3.7%
  14      macro_gdp_ann           Macro           0.3037     75.0000         0.1202     25.1413        3.4%
  15      mom_5                   Price           0.0012     44.0000         0.0009     14.6674        2.0%
  16      vol_ratio               Price           0.0009     38.0000         0.0006     12.6672        1.7%
  17      vol_ratio_252           Long-horizon      0.0007     33.0000         0.0018     11.0008        1.5%
  18      macro_inflation_ann     Macro           0.0075     27.0000         0.0557      9.0211        1.2%
  19      price_range             Price           0.0012     26.0000         0.0012      8.6675        1.2%
  20      ret_1                   Price           0.0012     22.0000         0.0003      7.3338        1.0%
  ────────────────────────────────────────────────────────────────────────────────────────────────────
          TOTAL                                                                        746.0000      100.0%

  Feature Group Summary:
  ──────────────────────────────────────────────────
  Short-horizon Price/Volume           226.6884  (30.4%)
  Long-horizon Trend/Context           406.7003  (54.5%)
  Macroeconomic                        112.6113  (15.1%)

In [20]:
# ─────────────────────────────────────────────
# 14. PORTFOLIO-LEVEL CUMULATIVE BACKTEST (Deliverable 3 - 2 Year Window)
# ─────────────────────────────────────────────

print(f"\n{'═'*110}")
print("  PORTFOLIO CUMULATIVE BACKTEST  (Last 2 Years)")
print("  Applies live blended weights to the most recent 504 trading days.")
if CASH_MODE:
    print("  ⚠  Cash Mode — showing hypothetical equal-weight market vs risk-free")
print(f"{'='*110}")

daily_actual_frames = {}
for name in names_list:
    d_bt = make_features(dfs[name], macro_daily)

    # We grab the last BACKTEST_DAYS (504 days = ~2 years) for the portfolio simulation
    final_test_idx  = np.arange(len(d_bt) - BACKTEST_DAYS, len(d_bt))
    test_df = d_bt.iloc[final_test_idx].copy().set_index("date")

    daily_actual_frames[name] = pd.Series(
        d_bt["Return"].values[final_test_idx],
        index=test_df.index, name=name
    )

actual_matrix = pd.DataFrame(daily_actual_frames).dropna()

if CASH_MODE:
    display_weights = np.ones(len(names_list)) / len(names_list)
    weight_label    = "Equal-Weight Market (hypothetical, NOT recommended)"
else:
    display_weights = opt_weights
    weight_label    = "Blended 1Y/3Y Optimised Portfolio"

port_actual_daily = actual_matrix.dot(display_weights)
port_monthly = pd.DataFrame({"Actual": port_actual_daily.resample("ME").sum()}).dropna()
port_monthly["Actual_Cum"] = (1 + port_monthly["Actual"]).cumprod() - 1

# Cash benchmark
monthly_rf                  = (1 + RF_RATE / 252) ** 21 - 1
port_monthly["Cash_Return"] = monthly_rf
port_monthly["Cash_Cum"]    = (1 + port_monthly["Cash_Return"]).cumprod() - 1

print(f"\n  Weights : {weight_label}")
if CASH_MODE:
    print(f"\n  {'Month':<12} {'Mkt Act Return':>16} {'Mkt Cum':>12} {'Cash Cum':>12} {'Cash Advantage':>16}")
    print(f"  {'─'*75}")
    for dt, row in port_monthly.iterrows():
        adv = row["Cash_Cum"] - row["Actual_Cum"]
        print(f"  {str(dt.date()):<12} {row['Actual']:>16.3%} {row['Actual_Cum']:>12.3%} {row['Cash_Cum']:>12.3%} {adv:>+16.3%}")
else:
    print(f"\n  {'Month':<12} {'Act Return':>12} {'Act Cumul':>12} {'Cash Cumul':>12} {'Active Alpha':>14}")
    print(f"  {'─'*70}")
    for dt, row in port_monthly.iterrows():
        alpha = row["Actual_Cum"] - row["Cash_Cum"]
        print(f"  {str(dt.date()):<12} {row['Actual']:>12.3%} {row['Actual_Cum']:>12.3%} {row['Cash_Cum']:>12.3%} {alpha:>+14.3%}")

final_actual_cum = port_monthly["Actual_Cum"].iloc[-1]
final_cash_cum   = port_monthly["Cash_Cum"].iloc[-1]
alpha_2y         = final_actual_cum - final_cash_cum

print(f"\n  {'─'*75}")
print(f"  2-Year Cumulative Return  (Portfolio) : {final_actual_cum:.2%}")
print(f"  2-Year Cumulative Return  (Cash)      : {final_cash_cum:.2%}")
print(f"  Active Alpha vs Cash                  : {alpha_2y:+.2%}")

if CASH_MODE:
    print(f"\n  ✦  By following the SELL signal and holding cash, you would have")
    print(f"     {'underperformed' if alpha_2y > 0 else 'outperformed'} the market by {abs(alpha_2y):.2%} over 2 years.")
else:
    ann_actual = (1 + final_actual_cum) ** (1 / 2) - 1
    ann_cash   = (1 + final_cash_cum)   ** (1 / 2) - 1
    print(f"  Annualised Return  (Portfolio)        : {ann_actual:.2%}")
    print(f"  Annualised Return  (Cash)             : {ann_cash:.2%}")

port_monthly.to_csv('output/backtest_portfolio.csv')
print(f"\n  → output/backtest_portfolio.csv saved.")
print(f"{'='*110}")

══════════════════════════════════════════════════════════════════════════════════════════════════════════════
  PORTFOLIO CUMULATIVE BACKTEST  (Last 2 Years)
  Applies live blended weights to the most recent 504 trading days.
  ⚠  Cash Mode — showing hypothetical equal-weight market vs risk-free
==============================================================================================================

  Weights : Equal-Weight Market (hypothetical, NOT recommended)

  Month          Mkt Act Return      Mkt Cum     Cash Cum   Cash Advantage
  ───────────────────────────────────────────────────────────────────────────
  2024-02-29            -0.441%      -0.441%       0.543%          +0.984%
  2024-03-31            -0.667%      -1.105%       1.089%          +2.194%
  2024-04-30            -2.439%      -3.517%       1.638%          +5.155%
  2024-05-31            -1.895%      -5.345%       2.190%          +7.535%
  2024-06-30             0.477%      -4.894%       2.745%          +7.639%
  2024-07-31             4.981%      -0.157%       3.303%          +3.460%
  2024-08-31             0.988%       0.829%       3.864%          +3.034%
  2024-09-30             0.530%       1.364%       4.428%          +3.064%
  2024-10-31            -6.343%      -5.065%       4.995%         +10.060%
  2024-11-30            -1.568%      -6.553%       5.565%         +12.119%
  2024-12-31            -2.867%      -9.233%       6.139%         +15.371%
  2025-01-31            -2.005%     -11.052%       6.715%         +17.767%
  2025-02-28            -4.234%     -14.818%       7.295%         +22.113%
  2025-03-31             5.572%     -10.072%       7.877%         +17.949%
  2025-04-30             4.046%      -6.434%       8.463%         +14.897%
  2025-05-31            -2.366%      -8.648%       9.052%         +17.700%
  2025-06-30             2.493%      -6.370%       9.644%         +16.015%
  2025-07-31            -1.056%      -7.359%      10.240%         +17.599%
  2025-08-31             0.274%      -7.106%      10.838%         +17.944%
  2025-09-30            -6.592%     -13.229%      11.440%         +24.669%
  2025-10-31             2.293%     -11.240%      12.046%         +23.285%
  2025-11-30             1.229%     -10.149%      12.654%         +22.803%
  2025-12-31            -0.076%     -10.217%      13.266%         +23.483%
  2026-01-31            -6.222%     -15.803%      13.881%         +29.684%
  2026-02-28            -6.645%     -21.398%      14.499%         +35.898%

  ───────────────────────────────────────────────────────────────────────────
  2-Year Cumulative Return  (Portfolio) : -21.40%
  2-Year Cumulative Return  (Cash)      : 14.50%
  Active Alpha vs Cash                  : -35.90%

  ✦  By following the SELL signal and holding cash, you would have
     outperformed the market by 35.90% over 2 years.

  → output/backtest_portfolio.csv saved.
==============================================================================================================